/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("AccountsListListReport journey");

        const defaultTableId = "";

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheAccountsListGenerated.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheAccountsListGenerated.onFilterBar().iCheckFilterField({ property: "Username" });
            Then.onTheAccountsListGenerated.onFilterBar().iCheckFilterField({ property: "FullName" });
            Then.onTheAccountsListGenerated.onFilterBar().iCheckFilterField({ property: "Email" });
            Then.onTheAccountsListGenerated.onFilterBar().iCheckFilterField({ property: "WorkerID" });
            Then.onTheAccountsListGenerated.onFilterBar().iCheckFilterField({ property: "Status" });
            Then.onTheAccountsListGenerated.onFilterBar().iCheckFilterField({ property: "LockedUntil" });
        });

        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onTheAccountsListGenerated.onFilterBar().iChangeSearchField("Search Term");
        //     When.onTheAccountsListGenerated.onFilterBar().iExecuteSearch();
        //     Then.onTheAccountsListGenerated.onTable(defaultTableId).iCheckRows();
        //     When.onTheAccountsListGenerated.onFilterBar().iChangeSearchField(undefined);
        //     Then.onTheAccountsListGenerated.onFilterBar().iCheckSearchField(undefined);
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            // When.onTheAccountsListGenerated.onTable(defaultTableId).iPressAction("Mở khóa tài khoản");
            Then.onTheAccountsListGenerated.onTable(defaultTableId).iCheckAction("Mở khóa tài khoản", { enabled: true });
            // When.onTheAccountsListGenerated.onTable(defaultTableId).iPressAction("Tạo tài khoản");
            Then.onTheAccountsListGenerated.onTable(defaultTableId).iCheckAction("Tạo tài khoản", { enabled: true });
            // When.onTheAccountsListGenerated.onTable(defaultTableId).iPressAction("Đổi mật khẩu");
            Then.onTheAccountsListGenerated.onTable(defaultTableId).iCheckAction("Đổi mật khẩu", { enabled: false });
            Then.onTheAccountsListGenerated.onTable(defaultTableId).iCheckColumns(undefined, {"Username":{"header":"Tên đăng nhập"},"FullName":{"header":"Họ và tên"},"Email":{"header":"Email"},"WorkerID":{"header":"Mã nhân viên"},"Status":{"header":"Trạng thái"},"PasswordChangeRequired":{"header":"Yêu cầu đổi mật khẩu"},"LastLoginAt":{"header":"Lần đăng nhập cuối"},"LockedUntil":{"header":"Khóa đến"},"CreatedAt":{"header":"Thời điểm tạo"}});
        });

        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            When.onTheAccountsListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheAccountsListGenerated.onTable(defaultTableId).iCheckRows();
            When.onTheAccountsListGenerated.onTable(defaultTableId).iPressRow(0);
            Then.onTheAccountsObjectPageGenerated.iSeeThisPage();
        });

        opaTest("Teardown", function (Given, When, Then) {
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});