/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("AccountsObjectPageObjectPage journey");

        opaTest("Navigate to AccountsObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheAccountsListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheAccountsListGenerated.onTable().iCheckRows();
            When.onTheAccountsListGenerated.onTable().iPressRow(0);

            Then.onTheAccountsObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check the number of sections of the Object Page", function (_Given, _When, Then) {
            Then.onTheAccountsObjectPageGenerated.iCheckNumberOfSections(2);
        });

        opaTest("Check the General section of the Object Page", function (_Given, When, Then) {
            When.onTheAccountsObjectPageGenerated.iPressSectionIconTabFilterButton("General");
            Then.onTheAccountsObjectPageGenerated.iCheckSection({ section: "General" });
            Then.onTheAccountsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "Username" });
            Then.onTheAccountsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "FullName" });
            Then.onTheAccountsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "Email" });
            Then.onTheAccountsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "WorkerID" });
            Then.onTheAccountsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "Status" });
            Then.onTheAccountsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "LockedUntil" });
        });

        opaTest("Check the Roles section of the Object Page", function (_Given, When, Then) {
            When.onTheAccountsObjectPageGenerated.iPressSectionIconTabFilterButton("Roles");
            Then.onTheAccountsObjectPageGenerated.iCheckSection({ section: "Roles" });
            Then.onTheAccountsObjectPageGenerated.onTable({ property: "_Roles" }).iCheckColumns(undefined, {"RoleID":{"header":"Mã chức danh"},"RoleName":{"header":"Tên chức danh"},"RoleStatus":{"header":"Trạng thái chức danh"}});
        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});