/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("AllocationTransactionsListListReport journey");

        const defaultTableId = "";

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheAllocationTransactionsListGenerated.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheAllocationTransactionsListGenerated.onFilterBar().iCheckFilterField({ property: "ProductionOrder" });
            Then.onTheAllocationTransactionsListGenerated.onFilterBar().iCheckFilterField({ property: "Operation" });
            Then.onTheAllocationTransactionsListGenerated.onFilterBar().iCheckFilterField({ property: "MaCongDoan" });
            Then.onTheAllocationTransactionsListGenerated.onFilterBar().iCheckFilterField({ property: "Plant" });
            Then.onTheAllocationTransactionsListGenerated.onFilterBar().iCheckFilterField({ property: "WorkCenter" });
            Then.onTheAllocationTransactionsListGenerated.onFilterBar().iCheckFilterField({ property: "WorkerID" });
            Then.onTheAllocationTransactionsListGenerated.onFilterBar().iCheckFilterField({ property: "WorkDate" });
            Then.onTheAllocationTransactionsListGenerated.onFilterBar().iCheckFilterField({ property: "ShiftID" });
            Then.onTheAllocationTransactionsListGenerated.onFilterBar().iCheckFilterField({ property: "TransactionType" });
            Then.onTheAllocationTransactionsListGenerated.onFilterBar().iCheckFilterField({ property: "TransactionStatus" });
            Then.onTheAllocationTransactionsListGenerated.onFilterBar().iCheckFilterField({ property: "SourceChannel" });
        });

        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onTheAllocationTransactionsListGenerated.onFilterBar().iChangeSearchField("Search Term");
        //     When.onTheAllocationTransactionsListGenerated.onFilterBar().iExecuteSearch();
        //     Then.onTheAllocationTransactionsListGenerated.onTable(defaultTableId).iCheckRows();
        //     When.onTheAllocationTransactionsListGenerated.onFilterBar().iChangeSearchField(undefined);
        //     Then.onTheAllocationTransactionsListGenerated.onFilterBar().iCheckSearchField(undefined);
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheAllocationTransactionsListGenerated.onTable(defaultTableId).iCheckColumns(undefined, {"ProductionOrder":{"header":"Lệnh sản xuất"},"Operation":{"header":"Công đoạn lệnh sản xuất"},"MaCongDoan":{"header":"Mã công đoạn"},"Plant":{"header":"Nhà máy"},"WorkCenter":{"header":"Trung tâm làm việc"},"TransactionType":{"header":"Loại giao dịch"},"WorkerID":{"header":"Mã nhân công"},"Quantity":{"header":"Số lượng"},"UnitOfMeasure":{"header":"Đơn vị tính"},"WorkDate":{"header":"Ngày làm việc"},"ShiftID":{"header":"Mã ca"},"ExecutedAt":{"header":"Thời điểm thực hiện UTC"},"TransactionStatus":{"header":"Trạng thái giao dịch"},"SourceChannel":{"header":"Nguồn giao dịch"},"ReasonText":{"header":"Nội dung lý do"}});
        });

        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            When.onTheAllocationTransactionsListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheAllocationTransactionsListGenerated.onTable(defaultTableId).iCheckRows();
            When.onTheAllocationTransactionsListGenerated.onTable(defaultTableId).iPressRow(0);
            Then.onTheAllocationTransactionsObjectPageGenerated.iSeeThisPage();
        });

        opaTest("Teardown", function (Given, When, Then) {
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});