/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("AllocationTransactionsObjectPageObjectPage journey");

        opaTest("Navigate to AllocationTransactionsObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheAllocationTransactionsListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheAllocationTransactionsListGenerated.onTable().iCheckRows();
            When.onTheAllocationTransactionsListGenerated.onTable().iPressRow(0);

            Then.onTheAllocationTransactionsObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check the General section of the Object Page", function (_Given, _When, Then) {
            Then.onTheAllocationTransactionsObjectPageGenerated.iCheckSection({ section: "General" });
            Then.onTheAllocationTransactionsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "ProductionOrder" });
            Then.onTheAllocationTransactionsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "Operation" });
            Then.onTheAllocationTransactionsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "MaCongDoan" });
            Then.onTheAllocationTransactionsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "Plant" });
            Then.onTheAllocationTransactionsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "WorkCenter" });
            Then.onTheAllocationTransactionsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "TransactionType" });
            Then.onTheAllocationTransactionsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "WorkerID" });
            Then.onTheAllocationTransactionsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "Quantity" });
            Then.onTheAllocationTransactionsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "UnitOfMeasure" });
            Then.onTheAllocationTransactionsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "WorkDate" });
            Then.onTheAllocationTransactionsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "ShiftID" });
            Then.onTheAllocationTransactionsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "ExecutedAt" });
            Then.onTheAllocationTransactionsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "TransactionStatus" });
            Then.onTheAllocationTransactionsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "SourceChannel" });
            Then.onTheAllocationTransactionsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "ReasonText" });
            Then.onTheAllocationTransactionsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "FromWorkerID" });
            Then.onTheAllocationTransactionsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "ToWorkerID" });
            Then.onTheAllocationTransactionsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "ExecutionDate" });
            Then.onTheAllocationTransactionsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "ReasonCode" });
            Then.onTheAllocationTransactionsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "OriginalTransactionType" });
            Then.onTheAllocationTransactionsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "OriginalTransactionUUID" });
            Then.onTheAllocationTransactionsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "TransactionUUID" });
            Then.onTheAllocationTransactionsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "OperationUUID" });
            Then.onTheAllocationTransactionsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "SyncItemUUID" });
            Then.onTheAllocationTransactionsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "ShiftStartAt" });
            Then.onTheAllocationTransactionsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "ShiftEndAt" });
            Then.onTheAllocationTransactionsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "ShiftTimeZone" });
            Then.onTheAllocationTransactionsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "ShiftValidFrom" });
            Then.onTheAllocationTransactionsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "ActorUserUUID" });
            Then.onTheAllocationTransactionsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "InitiatorSessionID" });
            Then.onTheAllocationTransactionsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "DeviceID" });
            Then.onTheAllocationTransactionsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "VerificationMethod" });
            Then.onTheAllocationTransactionsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "VerifiedWorkerUserUUID" });
            Then.onTheAllocationTransactionsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "WorkerVerifiedAt" });
            Then.onTheAllocationTransactionsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "CreatedBy" });
            Then.onTheAllocationTransactionsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "CreatedAt" });
        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});