/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("CongDoansListListReport journey");

        const defaultTableId = "";

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheCongDoansListGenerated.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheCongDoansListGenerated.onFilterBar().iCheckFilterField({ property: "MaCongDoan" });
            Then.onTheCongDoansListGenerated.onFilterBar().iCheckFilterField({ property: "TenCongDoan" });
            Then.onTheCongDoansListGenerated.onFilterBar().iCheckFilterField({ property: "BoPhan" });
            Then.onTheCongDoansListGenerated.onFilterBar().iCheckFilterField({ property: "ValidFrom" });
            Then.onTheCongDoansListGenerated.onFilterBar().iCheckFilterField({ property: "ValidTo" });
        });

        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onTheCongDoansListGenerated.onFilterBar().iChangeSearchField("Search Term");
        //     When.onTheCongDoansListGenerated.onFilterBar().iExecuteSearch();
        //     Then.onTheCongDoansListGenerated.onTable(defaultTableId).iCheckRows();
        //     When.onTheCongDoansListGenerated.onFilterBar().iChangeSearchField(undefined);
        //     Then.onTheCongDoansListGenerated.onFilterBar().iCheckSearchField(undefined);
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheCongDoansListGenerated.onTable(defaultTableId).iCheckColumns(undefined, {"MaCongDoan":{"header":"Mã công đoạn"},"TenCongDoan":{"header":"Tên công đoạn"},"BoPhan":{"header":"Bộ phận"},"DonGiaXM":{"header":"Đơn giá XM"},"DonGiaGC":{"header":"Đơn giá GC"},"ValidFrom":{"header":"Hiệu lực từ"},"ValidTo":{"header":"Hiệu lực đến"}});
        });

        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            When.onTheCongDoansListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheCongDoansListGenerated.onTable(defaultTableId).iCheckRows();
            When.onTheCongDoansListGenerated.onTable(defaultTableId).iPressRow(0);
            Then.onTheCongDoansObjectPageGenerated.iSeeThisPage();
        });

        opaTest("Teardown", function (Given, When, Then) {
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});