/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("CongDoansObjectPageObjectPage journey");

        opaTest("Navigate to CongDoansObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheCongDoansListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheCongDoansListGenerated.onTable().iCheckRows();
            When.onTheCongDoansListGenerated.onTable().iPressRow(0);

            Then.onTheCongDoansObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check the General section of the Object Page", function (_Given, _When, Then) {
            Then.onTheCongDoansObjectPageGenerated.iCheckSection({ section: "General" });
            Then.onTheCongDoansObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "MaCongDoan" });
            Then.onTheCongDoansObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "TenCongDoan" });
            Then.onTheCongDoansObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "BoPhan" });
            Then.onTheCongDoansObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "DonGiaXM" });
            Then.onTheCongDoansObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "DonGiaGC" });
            Then.onTheCongDoansObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "ValidFrom" });
            Then.onTheCongDoansObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "ValidTo" });
        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});