/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("DataObjectPageObjectPage journey");

        opaTest("Navigate to DataObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheManageFileListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheManageFileListGenerated.onTable().iCheckRows();
            When.onTheManageFileListGenerated.onTable().iPressRow(0);

            Then.onTheManageFileObjectPageGenerated.iSeeThisPage();
            Then.onTheManageFileObjectPageGenerated.onTable({ property: "_Data" }).iCheckRows();
            When.onTheManageFileObjectPageGenerated.onTable({ property: "_Data" }).iPressRow(0);

            Then.onTheDataObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheDataObjectPageGenerated.iCheckNumberOfSections(6);
            When.onTheDataObjectPageGenerated.iPressSectionIconTabFilterButton("General");
            Then.onTheDataObjectPageGenerated.iCheckSection({ section: "General" });
            Then.onTheDataObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "CompanyCode" });
            Then.onTheDataObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "AssetClass" });
            Then.onTheDataObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "PostCapitalization" });
            Then.onTheDataObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "FixedAssetDescription" });
            Then.onTheDataObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "AdditionalDescription" });
            Then.onTheDataObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "BaseUnitIsoCode" });
            Then.onTheDataObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "SerialNumber" });
            Then.onTheDataObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "OrderDate" });
            Then.onTheDataObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "EvalGroup1" });
            Then.onTheDataObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "EvalGroup2" });
            Then.onTheDataObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "EvalGroup3" });
            When.onTheDataObjectPageGenerated.iPressSectionIconTabFilterButton("Inventory");
            Then.onTheDataObjectPageGenerated.iCheckSection({ section: "Inventory" });
            Then.onTheDataObjectPageGenerated.onForm({ section: "Inventory" }).iCheckField({ property: "InventoryNumber" });
            Then.onTheDataObjectPageGenerated.onForm({ section: "Inventory" }).iCheckField({ property: "LastInventoryDate" });
            Then.onTheDataObjectPageGenerated.onForm({ section: "Inventory" }).iCheckField({ property: "InventoryNote" });
            Then.onTheDataObjectPageGenerated.onForm({ section: "Inventory" }).iCheckField({ property: "InventoryIsCounted" });
            When.onTheDataObjectPageGenerated.iPressSectionIconTabFilterButton("Account");
            Then.onTheDataObjectPageGenerated.iCheckSection({ section: "Account" });
            Then.onTheDataObjectPageGenerated.onForm({ section: "Account" }).iCheckField({ property: "CostCenter" });
            Then.onTheDataObjectPageGenerated.onForm({ section: "Account" }).iCheckField({ property: "ProfitCenter" });
            Then.onTheDataObjectPageGenerated.onForm({ section: "Account" }).iCheckField({ property: "Plant" });
            Then.onTheDataObjectPageGenerated.onForm({ section: "Account" }).iCheckField({ property: "Room" });
            Then.onTheDataObjectPageGenerated.onForm({ section: "Account" }).iCheckField({ property: "Segment" });
            Then.onTheDataObjectPageGenerated.onForm({ section: "Account" }).iCheckField({ property: "AssetLocation" });
            When.onTheDataObjectPageGenerated.iPressSectionIconTabFilterButton("Origin");
            Then.onTheDataObjectPageGenerated.iCheckSection({ section: "Origin" });
            Then.onTheDataObjectPageGenerated.onForm({ section: "Origin" }).iCheckField({ property: "Supplier" });
            Then.onTheDataObjectPageGenerated.onForm({ section: "Origin" }).iCheckField({ property: "AssetIsAcquiredUsed" });
            Then.onTheDataObjectPageGenerated.onForm({ section: "Origin" }).iCheckField({ property: "ManufacturerName" });
            When.onTheDataObjectPageGenerated.iPressSectionIconTabFilterButton("Valuation");
            Then.onTheDataObjectPageGenerated.iCheckSection({ section: "Valuation" });
            Then.onTheDataObjectPageGenerated.onForm({ section: "Valuation" }).iCheckField({ property: "CapitalizationDate" });
            Then.onTheDataObjectPageGenerated.onForm({ section: "Valuation" }).iCheckField({ property: "DeactivationDate" });
            Then.onTheDataObjectPageGenerated.onForm({ section: "Valuation" }).iCheckField({ property: "UsefulLifeYears" });
            Then.onTheDataObjectPageGenerated.onForm({ section: "Valuation" }).iCheckField({ property: "UsefulLifePeriods" });
            Then.onTheDataObjectPageGenerated.onForm({ section: "Valuation" }).iCheckField({ property: "DepreciationStartDate" });
            When.onTheDataObjectPageGenerated.iPressSectionIconTabFilterButton("Result");
            Then.onTheDataObjectPageGenerated.iCheckSection({ section: "Result" });
            Then.onTheDataObjectPageGenerated.onForm({ section: "Result" }).iCheckField({ property: "FixedAsset" });
            Then.onTheDataObjectPageGenerated.onForm({ section: "Result" }).iCheckField({ property: "MasterFixedAsset" });
            Then.onTheDataObjectPageGenerated.onForm({ section: "Result" }).iCheckField({ property: "Messagetype" });
            Then.onTheDataObjectPageGenerated.onForm({ section: "Result" }).iCheckField({ property: "Message" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});