/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("DataFileObjectPageObjectPage journey");

        opaTest("Navigate to DataFileObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheManageFileListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheManageFileListGenerated.onTable().iCheckRows();
            When.onTheManageFileListGenerated.onTable().iPressRow(0);

            Then.onTheManageFileObjectPageGenerated.iSeeThisPage();
            Then.onTheManageFileObjectPageGenerated.onTable({ property: "_DataFile" }).iCheckRows();
            When.onTheManageFileObjectPageGenerated.onTable({ property: "_DataFile" }).iPressRow(0);

            Then.onTheDataFileObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check the General section of the Object Page", function (_Given, _When, Then) {
            Then.onTheDataFileObjectPageGenerated.iCheckSection({ section: "General" });
            Then.onTheDataFileObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "Od" });
            Then.onTheDataFileObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "PlanGiDate" });
            Then.onTheDataFileObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "NhaCungCapVanTai" });
            Then.onTheDataFileObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "PhanLoaiPtvt" });
            Then.onTheDataFileObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "SoLuongPtvt" });
            Then.onTheDataFileObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "BienSoXe" });
            Then.onTheDataFileObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "SoContainer" });
            Then.onTheDataFileObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "SoSeal" });
            Then.onTheDataFileObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "TareWeight" });
            Then.onTheDataFileObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "Booking" });
            Then.onTheDataFileObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "NgayTauChay" });
            Then.onTheDataFileObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "NgayGioXuatHang" });
            Then.onTheDataFileObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "CutOffTime" });
            Then.onTheDataFileObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "GhiChuGiaoHang" });
            Then.onTheDataFileObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "TyGiaLoNoiDia" });
            Then.onTheDataFileObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "MessageType" });
            Then.onTheDataFileObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "Message" });
        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});