/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("dgthObjectPageObjectPage journey");

        opaTest("Navigate to dgthObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onThedgthListGenerated.onFilterBar().iExecuteSearch();
            Then.onThedgthListGenerated.onTable().iCheckRows();
            When.onThedgthListGenerated.onTable().iPressRow(0);

            Then.onThedgthObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onThedgthObjectPageGenerated.iCheckSection({ section: "GeneralInfo" });
            Then.onThedgthObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "Material" });
            Then.onThedgthObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "MaterialDescription" });
            Then.onThedgthObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "SalesOrder" });
            Then.onThedgthObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "SalesOrderItem" });
            Then.onThedgthObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "RoutingGroup" });
            Then.onThedgthObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "GroupCounter" });
            Then.onThedgthObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "DonGia" });
            Then.onThedgthObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "DonVi" });
            Then.onThedgthObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "Plant" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});