/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("dgthListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onThedgthListGenerated.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onThedgthListGenerated.onFilterBar().iCheckFilterField("Material");
            Then.onThedgthListGenerated.onFilterBar().iCheckFilterField("Plant");
            Then.onThedgthListGenerated.onFilterBar().iCheckFilterField("Sales Order");
            Then.onThedgthListGenerated.onFilterBar().iCheckFilterField("Sales Order Item");
        });

        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onThedgthListGenerated.onFilterBar().iChangeSearchField("Search Term");
        //     When.onThedgthListGenerated.onFilterBar().iExecuteSearch();
        //     Then.onThedgthListGenerated.onTable().iCheckRows();
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onThedgthListGenerated.onTable().iCheckColumns(undefined, {"Material":{"header":"Material"},"MaterialDescription":{"header":"Material Description"},"SalesOrder":{"header":"Sales Order"},"SalesOrderItem":{"header":"Sales Order Item"},"RoutingGroup":{"header":"Routing Group"},"GroupCounter":{"header":"Group Counter"},"DonGia":{"header":"Đơn giá"},"DonVi":{"header":"Đơn vị"},"Plant":{"header":"Plant"}});

        });



        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            When.onThedgthListGenerated.onFilterBar().iExecuteSearch();
            
            Then.onThedgthListGenerated.onTable().iCheckRows();

            When.onThedgthListGenerated.onTable().iPressRow(0);
            Then.onThedgthObjectPageGenerated.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});