/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("DnttListListListReport journey");

        const defaultTableId = "";

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheDnttListListGenerated.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheDnttListListGenerated.onFilterBar().iCheckFilterField({ property: "CompanyCode" });
            Then.onTheDnttListListGenerated.onFilterBar().iCheckFilterField({ property: "JeType" });
            Then.onTheDnttListListGenerated.onFilterBar().iCheckFilterField({ property: "TrgSpecGlInd" });
            Then.onTheDnttListListGenerated.onFilterBar().iCheckFilterField({ property: "Supplier" });
            Then.onTheDnttListListGenerated.onFilterBar().iCheckFilterField({ property: "DocumentNumber" });
            Then.onTheDnttListListGenerated.onFilterBar().iCheckFilterField({ property: "CreatedBy" });
            Then.onTheDnttListListGenerated.onFilterBar().iCheckFilterField({ property: "PostingDate" });
            Then.onTheDnttListListGenerated.onFilterBar().iCheckFilterField({ property: "Status" });
            Then.onTheDnttListListGenerated.onFilterBar().iCheckFilterField({ property: "CreatedOn" });
        });

        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onTheDnttListListGenerated.onFilterBar().iChangeSearchField("Search Term");
        //     When.onTheDnttListListGenerated.onFilterBar().iExecuteSearch();
        //     Then.onTheDnttListListGenerated.onTable(defaultTableId).iCheckRows();
        //     When.onTheDnttListListGenerated.onFilterBar().iChangeSearchField(undefined);
        //     Then.onTheDnttListListGenerated.onFilterBar().iCheckSearchField(undefined);
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheDnttListListGenerated.onTable(defaultTableId).iCheckColumns(undefined, {"Status":{"header":"Status"},"DocumentNumber":{"header":"Document number"},"DocumentSequenceNo":{"header":"Document SequenceNo"},"CompanyCode":{"header":"Company code"},"JeType":{"header":"JE Type"},"PostingDate":{"header":"Posting date"},"Currency":{"header":"Currency"},"HeaderText":{"header":"Header Text"},"Supplier":{"header":"Supplier"},"PaymentMethod":{"header":"Payment Method"},"PartnerBankType":{"header":"Partner Bank Type"},"BankAccount":{"header":"Bank Acc"},"Bank":{"header":"Bank"},"AccountHolder":{"header":"Acc.Holder"},"ProfitCenter":{"header":"Profit Center"},"DueOn":{"header":"Due On"},"TrgSpecGlInd":{"header":"Trg. Spec. G/L Ind"},"TotalAmount":{"header":"Tổng tiền thanh toán"},"TotalTax":{"header":"Tổng tiền thuế"},"Message":{"header":"Message"}});
        });

        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            When.onTheDnttListListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheDnttListListGenerated.onTable(defaultTableId).iCheckRows();
            When.onTheDnttListListGenerated.onTable(defaultTableId).iPressRow(0);
            Then.onTheDnttListObjectPageGenerated.iSeeThisPage();
        });

        opaTest("Teardown", function (Given, When, Then) {
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});