/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("DnttListObjectPageObjectPage journey");

        opaTest("Navigate to DnttListObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheDnttListListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheDnttListListGenerated.onTable().iCheckRows();
            When.onTheDnttListListGenerated.onTable().iPressRow(0);

            Then.onTheDnttListObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check the GeneratedFacet1 section of the Object Page", function (_Given, _When, Then) {
            Then.onTheDnttListObjectPageGenerated.iCheckSection({ section: "GeneratedFacet1" });
            Then.onTheDnttListObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "DocumentSequenceNo" });
            Then.onTheDnttListObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "TrgSpecGlInd" });
            Then.onTheDnttListObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Status" });
            Then.onTheDnttListObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "DocumentNumber" });
            Then.onTheDnttListObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "CompanyCode" });
            Then.onTheDnttListObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "JeType" });
            Then.onTheDnttListObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "PostingDate" });
            Then.onTheDnttListObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Currency" });
            Then.onTheDnttListObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "HeaderText" });
            Then.onTheDnttListObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Supplier" });
            Then.onTheDnttListObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "PaymentMethod" });
            Then.onTheDnttListObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "PartnerBankType" });
            Then.onTheDnttListObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "BankAccount" });
            Then.onTheDnttListObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Bank" });
            Then.onTheDnttListObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "AccountHolder" });
            Then.onTheDnttListObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "ProfitCenter" });
            Then.onTheDnttListObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "DueOn" });
            Then.onTheDnttListObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "TotalAmount" });
            Then.onTheDnttListObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "TotalTax" });
            Then.onTheDnttListObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Message" });
            Then.onTheDnttListObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "CreatedBy" });
            Then.onTheDnttListObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "CreatedOn" });
        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});