/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("FunctionsObjectPageObjectPage journey");

        opaTest("Navigate to FunctionsObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheFunctionsListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheFunctionsListGenerated.onTable().iCheckRows();
            When.onTheFunctionsListGenerated.onTable().iPressRow(0);

            Then.onTheFunctionsObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check the General section of the Object Page", function (_Given, _When, Then) {
            Then.onTheFunctionsObjectPageGenerated.iCheckSection({ section: "General" });
            Then.onTheFunctionsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "FuncID" });
            Then.onTheFunctionsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "FuncName" });
            Then.onTheFunctionsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "AppModule" });
        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});