/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ManageFileObjectPageObjectPage journey");

        opaTest("Navigate to ManageFileObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheManageFileListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheManageFileListGenerated.onTable().iCheckRows();
            When.onTheManageFileListGenerated.onTable().iPressRow(0);

            Then.onTheManageFileObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check the number of sections of the Object Page", function (_Given, _When, Then) {
            Then.onTheManageFileObjectPageGenerated.iCheckNumberOfSections(2);
        });

        opaTest("Check the General section of the Object Page", function (_Given, When, Then) {
            When.onTheManageFileObjectPageGenerated.iPressSectionIconTabFilterButton("General");
            Then.onTheManageFileObjectPageGenerated.iCheckSection({ section: "General" });
            Then.onTheManageFileObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "Attachment" });
            Then.onTheManageFileObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "LineCount" });
            Then.onTheManageFileObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "SuccessCount" });
            Then.onTheManageFileObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "Status" });
            Then.onTheManageFileObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "Message" });
            Then.onTheManageFileObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "CreatedBy" });
            Then.onTheManageFileObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "CreatedAt" });
            Then.onTheManageFileObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "LastChangedAt" });
            Then.onTheManageFileObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "FileName" });
        });

        opaTest("Check the HeaderRows section of the Object Page", function (_Given, When, Then) {
            When.onTheManageFileObjectPageGenerated.iPressSectionIconTabFilterButton("HeaderRows");
            Then.onTheManageFileObjectPageGenerated.iCheckSection({ section: "HeaderRows" });
            Then.onTheManageFileObjectPageGenerated.onTable({ property: "_DataFile" }).iCheckAction({ service: "com.sap.gateway.srvd.zui_m_od_head.v0001", action: "PostConfirm", unbound: false } /* , { enabled: true } */);
            // When.onTheManageFileObjectPageGenerated.onTable({ property: "_DataFile" }).iPressAction({ service: "com.sap.gateway.srvd.zui_m_od_head.v0001", action: "PostConfirm", unbound: false });
            Then.onTheManageFileObjectPageGenerated.onTable({ property: "_DataFile" }).iCheckColumns(undefined, {"Od":{"header":"OD"},"PlanGiDate":{"header":"Plan GI Date"},"NhaCungCapVanTai":{"header":"Nhà cung cấp vận tải"},"PhanLoaiPtvt":{"header":"Phân loại PTVT"},"SoLuongPtvt":{"header":"Số lượng PTVT"},"BienSoXe":{"header":"Biển số xe"},"SoContainer":{"header":"Số container"},"SoSeal":{"header":"Số seal"},"TareWeight":{"header":"Tare Weight"},"Booking":{"header":"Booking"},"NgayTauChay":{"header":"Ngày tàu chạy"},"NgayGioXuatHang":{"header":"Ngày giờ xuất hàng"},"CutOffTime":{"header":"Cut-off Time"},"GhiChuGiaoHang":{"header":"Ghi chú giao hàng"},"TyGiaLoNoiDia":{"header":"Tỷ giá lô nội địa"},"MessageType":{"header":"Result Type"},"Message":{"header":"Result Message"}});
        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});