/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ManageFileListListReport journey");

        const defaultTableId = "";

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheManageFileListGenerated.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheManageFileListGenerated.onFilterBar().iCheckFilterField({ property: "FileName" });
            Then.onTheManageFileListGenerated.onFilterBar().iCheckFilterField({ property: "Status" });
            Then.onTheManageFileListGenerated.onFilterBar().iCheckFilterField({ property: "CreatedBy" });
            Then.onTheManageFileListGenerated.onFilterBar().iCheckFilterField({ property: "CreatedAt" });
        });

        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onTheManageFileListGenerated.onFilterBar().iChangeSearchField("Search Term");
        //     When.onTheManageFileListGenerated.onFilterBar().iExecuteSearch();
        //     Then.onTheManageFileListGenerated.onTable(defaultTableId).iCheckRows();
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheManageFileListGenerated.onTable(defaultTableId).iCheckCreate({ visible: true });
            // When.onTheManageFileListGenerated.onTable(defaultTableId).iPressCreate();
            // When.onTheManageFileListGenerated.onTable(defaultTableId).iPressDelete();
            Then.onTheManageFileListGenerated.onTable(defaultTableId).iCheckDelete({ visible: true });
            // When.onTheManageFileListGenerated.onTable(defaultTableId).iPressAction("Upload Excel");
            Then.onTheManageFileListGenerated.onTable(defaultTableId).iCheckAction("Upload Excel", { enabled: true });
            // When.onTheManageFileListGenerated.onTable(defaultTableId).iPressAction("Process File");
            Then.onTheManageFileListGenerated.onTable(defaultTableId).iCheckAction("Process File", { enabled: false });
            Then.onTheManageFileListGenerated.onTable(defaultTableId).iCheckColumns(undefined, {"FileName":{"header":"File Name"},"Status":{"header":"Status"},"Message":{"header":"Message"},"CreatedBy":{"header":"User Name"},"CreatedAt":{"header":"Time Stamp"},"OverallStatusText":{"header":"Status"},"Uuid":{"header":"UUID"}});
        });

        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            When.onTheManageFileListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheManageFileListGenerated.onTable(defaultTableId).iCheckRows();
            When.onTheManageFileListGenerated.onTable(defaultTableId).iPressRow(0);
            Then.onTheManageFileObjectPageGenerated.iSeeThisPage();
        });

        opaTest("Teardown", function (Given, When, Then) {
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});