/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ManageFileListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheManageFileList.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheManageFileList.onFilterBar().iCheckFilterField("Status");
            Then.onTheManageFileList.onFilterBar().iCheckFilterField("File name");
            Then.onTheManageFileList.onFilterBar().iCheckFilterField("Total line of File");
            Then.onTheManageFileList.onFilterBar().iCheckFilterField("Created By");
            Then.onTheManageFileList.onFilterBar().iCheckFilterField("Created On");
            Then.onTheManageFileList.onFilterBar().iCheckFilterField("Changed By");
            Then.onTheManageFileList.onFilterBar().iCheckFilterField("Changed On");
        });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            // Then.ontheManageFileList.onTable().iPressDelete();
            Then.onTheManageFileList.onTable().iCheckDelete({ visible: true });
            // Then.onTheManageFileList.onTable().iPressAction("Download Template");
            Then.onTheManageFileList.onTable().iCheckAction("Download Template", { enabled: true });
            Then.onTheManageFileList.onTable().iCheckColumns(undefined, {"Uuid":{"header":"UUID"},"Zcount":{"header":"No."},"Status":{"header":"Status"},"Attachment":{"header":"Attachment"},"Mimetype":{"header":"Mime type"},"Filename":{"header":"File name"},"Countline":{"header":"Total line of File"},"Createdbyuser":{"header":"Created By"},"Createddate":{"header":"Created On"},"Changedbyuser":{"header":"Changed By"},"Changeddate":{"header":"Changed On"}});

        });



        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            When.onTheManageFileList.onFilterBar().iExecuteSearch();
            
            Then.onTheManageFileList.onTable().iCheckRows();

            When.onTheManageFileList.onTable().iPressRow(0);
            Then.onTheManageFileObjectPage.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});