/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ManageFilePR1ListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheManageFilePR1ListGenerated.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheManageFilePR1ListGenerated.onFilterBar().iCheckFilterField("Status");
            Then.onTheManageFilePR1ListGenerated.onFilterBar().iCheckFilterField("File name");
            Then.onTheManageFilePR1ListGenerated.onFilterBar().iCheckFilterField("Total line of File");
            Then.onTheManageFilePR1ListGenerated.onFilterBar().iCheckFilterField("Created By");
            Then.onTheManageFilePR1ListGenerated.onFilterBar().iCheckFilterField("Created On");
            Then.onTheManageFilePR1ListGenerated.onFilterBar().iCheckFilterField("Changed By");
            Then.onTheManageFilePR1ListGenerated.onFilterBar().iCheckFilterField("Changed On");
        });

        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onTheManageFilePR1ListGenerated.onFilterBar().iChangeSearchField("Search Term");
        //     When.onTheManageFilePR1ListGenerated.onFilterBar().iExecuteSearch();
        //     Then.onTheManageFilePR1ListGenerated.onTable().iCheckRows();
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            // Then.onTheManageFilePR1ListGenerated.onTable().iPressDelete();
            Then.onTheManageFilePR1ListGenerated.onTable().iCheckDelete({ visible: true });
            // Then.onTheManageFilePR1ListGenerated.onTable().iPressAction("Download Template");
            Then.onTheManageFilePR1ListGenerated.onTable().iCheckAction("Download Template", { enabled: true });
            Then.onTheManageFilePR1ListGenerated.onTable().iCheckColumns(undefined, {"Uuid":{"header":"UUID"},"Zcount":{"header":"No."},"Status":{"header":"Status"},"Attachment":{"header":"Attachment"},"Mimetype":{"header":"Mime type"},"Filename":{"header":"File name"},"Countline":{"header":"Total line of File"},"Createdbyuser":{"header":"Created By"},"Createddate":{"header":"Created On"},"Changedbyuser":{"header":"Changed By"},"Changeddate":{"header":"Changed On"}});

        });



        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            When.onTheManageFilePR1ListGenerated.onFilterBar().iExecuteSearch();
            
            Then.onTheManageFilePR1ListGenerated.onTable().iCheckRows();

            When.onTheManageFilePR1ListGenerated.onTable().iPressRow(0);
            Then.onTheManageFilePR1ObjectPageGenerated.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});