/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ManageFileObjectPageObjectPage journey");

        opaTest("Navigate to ManageFileObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheManageFileListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheManageFileListGenerated.onTable().iCheckRows();
            When.onTheManageFileListGenerated.onTable().iPressRow(0);

            Then.onTheManageFileObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheManageFileObjectPageGenerated.iCheckNumberOfSections(2);
            When.onTheManageFileObjectPageGenerated.iPressSectionIconTabFilterButton("Header");
            Then.onTheManageFileObjectPageGenerated.iCheckSection({ section: "Header" });
            Then.onTheManageFileObjectPageGenerated.onForm({ section: "Header" }).iCheckField({ property: "Filename" });
            Then.onTheManageFileObjectPageGenerated.onForm({ section: "Header" }).iCheckField({ property: "Status" });
            Then.onTheManageFileObjectPageGenerated.onForm({ section: "Header" }).iCheckField({ property: "Mimetype" });
            Then.onTheManageFileObjectPageGenerated.onForm({ section: "Header" }).iCheckField({ property: "Attachment" });
            Then.onTheManageFileObjectPageGenerated.onForm({ section: "Header" }).iCheckField({ property: "Countline" });
            Then.onTheManageFileObjectPageGenerated.onForm({ section: "Header" }).iCheckField({ property: "Zcount" });
            Then.onTheManageFileObjectPageGenerated.onForm({ section: "Header" }).iCheckField({ property: "ZcountDone" });
            When.onTheManageFileObjectPageGenerated.iPressSectionIconTabFilterButton("Data");
            Then.onTheManageFileObjectPageGenerated.iCheckSection({ section: "Data" });
            Then.onTheManageFileObjectPageGenerated.onTable({ property: "_Data" }).iCheckColumns(undefined, {"Status":{"header":"Status"},"CompanyCode":{"header":"Company Code"},"AssetClass":{"header":"Asset Class"},"FixedAssetDescription":{"header":"Asset Description"},"CostCenter":{"header":"Cost Center"},"Plant":{"header":"Plant"},"FixedAsset":{"header":"Fixed Asset"},"Message":{"header":"Message"}});
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});