/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ManageFileObjectPageObjectPage journey");

        opaTest("Navigate to ManageFileObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheManageFileListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheManageFileListGenerated.onTable().iCheckRows();
            When.onTheManageFileListGenerated.onTable().iPressRow(0);

            Then.onTheManageFileObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheManageFileObjectPageGenerated.iCheckNumberOfSections(2);
            When.onTheManageFileObjectPageGenerated.iPressSectionIconTabFilterButton("General");
            Then.onTheManageFileObjectPageGenerated.iCheckSection({ section: "General" });
            //When.onTheManageFileObjectPageGenerated.iGoToSection({ section: "General", subSection: "BasicInfo" });
            Then.onTheManageFileObjectPageGenerated.iCheckSubSection({ section: "BasicInfo" });
            Then.onTheManageFileObjectPageGenerated.onForm({ section: "BasicInfo" }).iCheckField({ property: "FileName" });
            Then.onTheManageFileObjectPageGenerated.onForm({ section: "BasicInfo" }).iCheckField({ property: "Status" });
            Then.onTheManageFileObjectPageGenerated.onForm({ section: "BasicInfo" }).iCheckField({ property: "Message" });
            Then.onTheManageFileObjectPageGenerated.onForm({ section: "BasicInfo" }).iCheckField({ property: "CreatedBy" });
            Then.onTheManageFileObjectPageGenerated.onForm({ section: "BasicInfo" }).iCheckField({ property: "CreatedAt" });
            When.onTheManageFileObjectPageGenerated.iPressSectionIconTabFilterButton("HeaderRows");
            Then.onTheManageFileObjectPageGenerated.iCheckSection({ section: "HeaderRows" });
            Then.onTheManageFileObjectPageGenerated.onTable({ property: "_DataFile" }).iCheckColumns(undefined, {"OverallStatusText":{"header":"Status"}});
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});