/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ManageFilePR1ObjectPageObjectPage journey");

        opaTest("Navigate to ManageFilePR1ObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheManageFilePR1ListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheManageFilePR1ListGenerated.onTable().iCheckRows();
            When.onTheManageFilePR1ListGenerated.onTable().iPressRow(0);

            Then.onTheManageFilePR1ObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheManageFilePR1ObjectPageGenerated.iCheckNumberOfSections(2);
            When.onTheManageFilePR1ObjectPageGenerated.iPressSectionIconTabFilterButton("General");
            Then.onTheManageFilePR1ObjectPageGenerated.iCheckSection({ section: "General" });
            When.onTheManageFilePR1ObjectPageGenerated.iPressSectionIconTabFilterButton("Items");
            Then.onTheManageFilePR1ObjectPageGenerated.iCheckSection({ section: "Items" });
            Then.onTheManageFilePR1ObjectPageGenerated.onTable({ property: "_DataFile" }).iCheckAction("Post Document" /* , { enabled: true } */);
            // When.onTheManageFilePR1ObjectPageGenerated.onTable({ property: "_DataFile" }).iPressAction("Post Document");
            Then.onTheManageFilePR1ObjectPageGenerated.onTable({ property: "_DataFile" }).iCheckAction("Set Job" /* , { enabled: true } */);
            // When.onTheManageFilePR1ObjectPageGenerated.onTable({ property: "_DataFile" }).iPressAction("Set Job");
            Then.onTheManageFilePR1ObjectPageGenerated.onTable({ property: "_DataFile" }).iCheckColumns(undefined, {"Uuid":{"header":"UUID"},"Messagetype":{"header":"Message Type"},"Type":{"header":"Type"},"PurchaseRequisition":{"header":"PR"},"PurchaseRequisitionType":{"header":"PR Type"},"PurReqnDescription":{"header":"Diễn giải PR"},"PurReqnHeaderNote":{"header":"Note Text PR"},"PurchaseRequisitionItem":{"header":"PR Item"},"Material":{"header":"Material"},"RequestedQuantity":{"header":"Số lượng"},"BaseUnit":{"header":"Đơn vị"},"Plant":{"header":"Plant xuất hàng"},"StorageLocation":{"header":"Kho xuất"},"PurchaseRequisitionPrice":{"header":"Đơn giá"},"PurReqnPriceQuantity":{"header":"Per"},"PurReqnItemCurrency":{"header":"Loại tiền tệ"},"PurchasingGroup":{"header":"Nhóm mua hàng"},"DeliveryDate":{"header":"Ngày giao hàng"},"CreatedBy":{"header":"Created By"},"CreatedAt":{"header":"Created On"},"Message":{"header":"Message Text"}});
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});