/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ManageFilePOSubCompObjectPageObjectPage journey");

        opaTest("Navigate to ManageFilePOSubCompObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onTheManageFilePOSubCompListGenerated.onFilterBar().iExecuteSearch();

            Then.onTheManageFilePOSubCompListGenerated.onTable().iCheckRows();
            When.onTheManageFilePOSubCompListGenerated.onTable().iPressRow(0);

            Then.onTheManageFilePOSubCompObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheManageFilePOSubCompObjectPageGenerated.iCheckNumberOfSections(2);
            When.onTheManageFilePOSubCompObjectPageGenerated.iPressSectionIconTabFilterButton("General");
            Then.onTheManageFilePOSubCompObjectPageGenerated.iCheckSection({ section: "General" });
            When.onTheManageFilePOSubCompObjectPageGenerated.iPressSectionIconTabFilterButton("Items");
            Then.onTheManageFilePOSubCompObjectPageGenerated.iCheckSection({ section: "Items" });
            Then.onTheManageFilePOSubCompObjectPageGenerated.onTable({ property: "_DataFile" }).iCheckAction("Post Document" /* , { enabled: true } */);
            // When.onTheManageFilePOSubCompObjectPageGenerated.onTable({ property: "_DataFile" }).iPressAction("Post Document");
            Then.onTheManageFilePOSubCompObjectPageGenerated.onTable({ property: "_DataFile" }).iCheckAction("Set Job" /* , { enabled: true } */);
            // When.onTheManageFilePOSubCompObjectPageGenerated.onTable({ property: "_DataFile" }).iPressAction("Set Job");
            Then.onTheManageFilePOSubCompObjectPageGenerated.onTable({ property: "_DataFile" }).iCheckColumns({"Uuid":{"header":"UUID"},"Messagetype":{"header":"Message Type"},"Type":{"header":"Type"},"PurchaseOrder":{"header":"Purchase Order"},"PurchaseOrderItem":{"header":"Purchase Order Item"},"ScheduleLine":{"header":"Schedule Line"},"ReservationItem":{"header":"Reservation Item"},"Material":{"header":"Material"},"QuantityInEntryUnit":{"header":"Quantity in Entry Unit"},"EntryUnit":{"header":"Entry Unit"},"Plant":{"header":"Plant"},"StorageLocation":{"header":"Storage Location"},"CreatedBy":{"header":"Created By"},"CreatedAt":{"header":"Created On"},"Message":{"header":"Message Text"}});
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});