/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("OperationAllocationsObjectPageObjectPage journey");

        opaTest("Navigate to OperationAllocationsObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheOperationAllocationsListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheOperationAllocationsListGenerated.onTable().iCheckRows();
            When.onTheOperationAllocationsListGenerated.onTable().iPressRow(0);

            Then.onTheOperationAllocationsObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check the General section of the Object Page", function (_Given, _When, Then) {
            Then.onTheOperationAllocationsObjectPageGenerated.iCheckSection({ section: "General" });
            Then.onTheOperationAllocationsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "ProductionOrder" });
            Then.onTheOperationAllocationsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "Operation" });
            Then.onTheOperationAllocationsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "MaCongDoan" });
            Then.onTheOperationAllocationsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "Plant" });
            Then.onTheOperationAllocationsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "WorkCenter" });
            Then.onTheOperationAllocationsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "OperationQuantity" });
            Then.onTheOperationAllocationsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "UnitOfMeasure" });
            Then.onTheOperationAllocationsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "OperationStatus" });
            Then.onTheOperationAllocationsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "OperationUUID" });
            Then.onTheOperationAllocationsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "CreatedBy" });
            Then.onTheOperationAllocationsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "CreatedAt" });
            Then.onTheOperationAllocationsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "LastChangedBy" });
            Then.onTheOperationAllocationsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "LocalLastChangedAt" });
        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});