/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("OperationAllocationsListListReport journey");

        const defaultTableId = "";

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheOperationAllocationsListGenerated.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheOperationAllocationsListGenerated.onFilterBar().iCheckFilterField({ property: "ProductionOrder" });
            Then.onTheOperationAllocationsListGenerated.onFilterBar().iCheckFilterField({ property: "MaCongDoan" });
            Then.onTheOperationAllocationsListGenerated.onFilterBar().iCheckFilterField({ property: "Plant" });
            Then.onTheOperationAllocationsListGenerated.onFilterBar().iCheckFilterField({ property: "WorkCenter" });
        });

        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onTheOperationAllocationsListGenerated.onFilterBar().iChangeSearchField("Search Term");
        //     When.onTheOperationAllocationsListGenerated.onFilterBar().iExecuteSearch();
        //     Then.onTheOperationAllocationsListGenerated.onTable(defaultTableId).iCheckRows();
        //     When.onTheOperationAllocationsListGenerated.onFilterBar().iChangeSearchField(undefined);
        //     Then.onTheOperationAllocationsListGenerated.onFilterBar().iCheckSearchField(undefined);
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            // When.onTheOperationAllocationsListGenerated.onTable(defaultTableId).iPressAction("Điều chỉnh xác nhận");
            Then.onTheOperationAllocationsListGenerated.onTable(defaultTableId).iCheckAction("Điều chỉnh xác nhận", { enabled: false });
            Then.onTheOperationAllocationsListGenerated.onTable(defaultTableId).iCheckColumns(undefined, {"ProductionOrder":{"header":"Lệnh sản xuất"},"Operation":{"header":"Công đoạn"},"MaCongDoan":{"header":"Mã công đoạn"},"Plant":{"header":"Nhà máy"},"WorkCenter":{"header":"Tổ/Work Center"},"OperationQuantity":{"header":"Sản lượng công đoạn"},"UnitOfMeasure":{"header":"ĐVT"},"OperationStatus":{"header":"Trạng thái"}});
        });

        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            When.onTheOperationAllocationsListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheOperationAllocationsListGenerated.onTable(defaultTableId).iCheckRows();
            When.onTheOperationAllocationsListGenerated.onTable(defaultTableId).iPressRow(0);
            Then.onTheOperationAllocationsObjectPageGenerated.iSeeThisPage();
        });

        opaTest("Teardown", function (Given, When, Then) {
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});