/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("RolesObjectPageObjectPage journey");

        opaTest("Navigate to RolesObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheRolesListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheRolesListGenerated.onTable().iCheckRows();
            When.onTheRolesListGenerated.onTable().iPressRow(0);

            Then.onTheRolesObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check the number of sections of the Object Page", function (_Given, _When, Then) {
            Then.onTheRolesObjectPageGenerated.iCheckNumberOfSections(3);
        });

        opaTest("Check the General section of the Object Page", function (_Given, When, Then) {
            When.onTheRolesObjectPageGenerated.iPressSectionIconTabFilterButton("General");
            Then.onTheRolesObjectPageGenerated.iCheckSection({ section: "General" });
            Then.onTheRolesObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "RoleID" });
            Then.onTheRolesObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "RoleName" });
            Then.onTheRolesObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "Status" });
        });

        opaTest("Check the Functions section of the Object Page", function (_Given, When, Then) {
            When.onTheRolesObjectPageGenerated.iPressSectionIconTabFilterButton("Functions");
            Then.onTheRolesObjectPageGenerated.iCheckSection({ section: "Functions" });
            Then.onTheRolesObjectPageGenerated.onTable({ property: "_Functions" }).iCheckColumns(undefined, {"FuncID":{"header":"Mã chức năng"},"FuncName":{"header":"Tên chức năng"},"AppModule":{"header":"Phân hệ ứng dụng"}});
        });

        opaTest("Check the WorkAssignments section of the Object Page", function (_Given, When, Then) {
            When.onTheRolesObjectPageGenerated.iPressSectionIconTabFilterButton("WorkAssignments");
            Then.onTheRolesObjectPageGenerated.iCheckSection({ section: "WorkAssignments" });
            Then.onTheRolesObjectPageGenerated.onTable({ property: "_WorkAssignments" }).iCheckColumns(undefined, {"WorkID":{"header":"Work ID"},"WorkName":{"header":"Tên vị trí làm việc"},"Plant":{"header":"Nhà máy"},"WorkCenter":{"header":"Trung tâm làm việc"},"BoPhan":{"header":"Bộ phận"},"Location":{"header":"Địa điểm"}});
        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});