/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("RolesListListReport journey");

        const defaultTableId = "";

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheRolesListGenerated.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheRolesListGenerated.onFilterBar().iCheckFilterField({ property: "RoleID" });
            Then.onTheRolesListGenerated.onFilterBar().iCheckFilterField({ property: "RoleName" });
            Then.onTheRolesListGenerated.onFilterBar().iCheckFilterField({ property: "Status" });
        });

        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onTheRolesListGenerated.onFilterBar().iChangeSearchField("Search Term");
        //     When.onTheRolesListGenerated.onFilterBar().iExecuteSearch();
        //     Then.onTheRolesListGenerated.onTable(defaultTableId).iCheckRows();
        //     When.onTheRolesListGenerated.onFilterBar().iChangeSearchField(undefined);
        //     Then.onTheRolesListGenerated.onFilterBar().iCheckSearchField(undefined);
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheRolesListGenerated.onTable(defaultTableId).iCheckColumns(undefined, {"RoleID":{"header":"Mã chức danh"},"RoleName":{"header":"Tên chức danh"},"Status":{"header":"Trạng thái"},"CreatedBy":{"header":"Người tạo"},"CreatedAt":{"header":"Thời điểm tạo"}});
        });

        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            When.onTheRolesListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheRolesListGenerated.onTable(defaultTableId).iCheckRows();
            When.onTheRolesListGenerated.onTable(defaultTableId).iPressRow(0);
            Then.onTheRolesObjectPageGenerated.iSeeThisPage();
        });

        opaTest("Teardown", function (Given, When, Then) {
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});