/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ShiftsListListReport journey");

        const defaultTableId = "";

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheShiftsListGenerated.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheShiftsListGenerated.onFilterBar().iCheckFilterField({ property: "Plant" });
            Then.onTheShiftsListGenerated.onFilterBar().iCheckFilterField({ property: "ShiftID" });
            Then.onTheShiftsListGenerated.onFilterBar().iCheckFilterField({ property: "ShiftName" });
            Then.onTheShiftsListGenerated.onFilterBar().iCheckFilterField({ property: "ValidFrom" });
            Then.onTheShiftsListGenerated.onFilterBar().iCheckFilterField({ property: "IsActive" });
        });

        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onTheShiftsListGenerated.onFilterBar().iChangeSearchField("Search Term");
        //     When.onTheShiftsListGenerated.onFilterBar().iExecuteSearch();
        //     Then.onTheShiftsListGenerated.onTable(defaultTableId).iCheckRows();
        //     When.onTheShiftsListGenerated.onFilterBar().iChangeSearchField(undefined);
        //     Then.onTheShiftsListGenerated.onFilterBar().iCheckSearchField(undefined);
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheShiftsListGenerated.onTable(defaultTableId).iCheckColumns(undefined, {"Plant":{"header":"Nhà máy"},"ShiftID":{"header":"Mã ca"},"ShiftName":{"header":"Tên ca"},"StartTime":{"header":"Giờ bắt đầu"},"EndTime":{"header":"Giờ kết thúc"},"EndDayOffset":{"header":"Ngày kết thúc"},"SAPTimeZone":{"header":"Múi giờ SAP"},"ValidFrom":{"header":"Hiệu lực từ"},"ValidTo":{"header":"Hiệu lực đến"},"IsActive":{"header":"Trạng thái"}});
        });

        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            When.onTheShiftsListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheShiftsListGenerated.onTable(defaultTableId).iCheckRows();
            When.onTheShiftsListGenerated.onTable(defaultTableId).iPressRow(0);
            Then.onTheShiftsObjectPageGenerated.iSeeThisPage();
        });

        opaTest("Teardown", function (Given, When, Then) {
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});