/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ShiftsObjectPageObjectPage journey");

        opaTest("Navigate to ShiftsObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheShiftsListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheShiftsListGenerated.onTable().iCheckRows();
            When.onTheShiftsListGenerated.onTable().iPressRow(0);

            Then.onTheShiftsObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check the General section of the Object Page", function (_Given, _When, Then) {
            Then.onTheShiftsObjectPageGenerated.iCheckSection({ section: "General" });
            Then.onTheShiftsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "Plant" });
            Then.onTheShiftsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "ShiftID" });
            Then.onTheShiftsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "ShiftName" });
            Then.onTheShiftsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "StartTime" });
            Then.onTheShiftsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "EndTime" });
            Then.onTheShiftsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "EndDayOffset" });
            Then.onTheShiftsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "SAPTimeZone" });
            Then.onTheShiftsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "ValidFrom" });
            Then.onTheShiftsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "ValidTo" });
            Then.onTheShiftsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "IsActive" });
            Then.onTheShiftsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "CreatedBy" });
            Then.onTheShiftsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "CreatedAt" });
            Then.onTheShiftsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "LastChangedBy" });
            Then.onTheShiftsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "LastChangedAt" });
        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});