/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("WorkContextsListListReport journey");

        const defaultTableId = "";

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheWorkContextsListGenerated.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheWorkContextsListGenerated.onFilterBar().iCheckFilterField({ property: "WorkID" });
            Then.onTheWorkContextsListGenerated.onFilterBar().iCheckFilterField({ property: "WorkName" });
            Then.onTheWorkContextsListGenerated.onFilterBar().iCheckFilterField({ property: "Plant" });
            Then.onTheWorkContextsListGenerated.onFilterBar().iCheckFilterField({ property: "WorkCenter" });
            Then.onTheWorkContextsListGenerated.onFilterBar().iCheckFilterField({ property: "IsActive" });
        });

        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onTheWorkContextsListGenerated.onFilterBar().iChangeSearchField("Search Term");
        //     When.onTheWorkContextsListGenerated.onFilterBar().iExecuteSearch();
        //     Then.onTheWorkContextsListGenerated.onTable(defaultTableId).iCheckRows();
        //     When.onTheWorkContextsListGenerated.onFilterBar().iChangeSearchField(undefined);
        //     Then.onTheWorkContextsListGenerated.onFilterBar().iCheckSearchField(undefined);
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheWorkContextsListGenerated.onTable(defaultTableId).iCheckColumns(undefined, {"WorkID":{"header":"Work ID"},"WorkName":{"header":"Tên vị trí làm việc"},"Plant":{"header":"Nhà máy"},"WorkCenter":{"header":"Trung tâm làm việc"},"BoPhan":{"header":"Bộ phận"},"Location":{"header":"Địa điểm"},"IsActive":{"header":"Đang hoạt động"}});
        });

        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            When.onTheWorkContextsListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheWorkContextsListGenerated.onTable(defaultTableId).iCheckRows();
            When.onTheWorkContextsListGenerated.onTable(defaultTableId).iPressRow(0);
            Then.onTheWorkContextsObjectPageGenerated.iSeeThisPage();
        });

        opaTest("Teardown", function (Given, When, Then) {
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});