/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("WorkContextsObjectPageObjectPage journey");

        opaTest("Navigate to WorkContextsObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheWorkContextsListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheWorkContextsListGenerated.onTable().iCheckRows();
            When.onTheWorkContextsListGenerated.onTable().iPressRow(0);

            Then.onTheWorkContextsObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check the General section of the Object Page", function (_Given, _When, Then) {
            Then.onTheWorkContextsObjectPageGenerated.iCheckSection({ section: "General" });
            Then.onTheWorkContextsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "WorkID" });
            Then.onTheWorkContextsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "WorkName" });
            Then.onTheWorkContextsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "Plant" });
            Then.onTheWorkContextsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "WorkCenter" });
            Then.onTheWorkContextsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "BoPhan" });
            Then.onTheWorkContextsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "Location" });
            Then.onTheWorkContextsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "IsActive" });
        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});