/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ZC_D_MCH_SO_U_DATAObjectPageObjectPage journey");

        opaTest("Navigate to ZC_D_MCH_SO_U_DATAObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onTheZC_M_MCH_SO_U_FILEListGenerated.onFilterBar().iExecuteSearch();

            Then.onTheZC_M_MCH_SO_U_FILEListGenerated.onTable().iCheckRows();
            When.onTheZC_M_MCH_SO_U_FILEListGenerated.onTable().iPressRow(0);

            Then.onTheZC_M_MCH_SO_U_FILEObjectPageGenerated.iSeeThisPage();
            Then.onTheZC_M_MCH_SO_U_FILEObjectPageGenerated.onTable({ property: "_DataFile" }).iCheckRows();
            When.onTheZC_M_MCH_SO_U_FILEObjectPageGenerated.onTable({ property: "_DataFile" }).iPressRow(0);

            Then.onTheZC_D_MCH_SO_U_DATAObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheZC_D_MCH_SO_U_DATAObjectPageGenerated.iCheckNumberOfSections(2);
            When.onTheZC_D_MCH_SO_U_DATAObjectPageGenerated.iPressSectionIconTabFilterButton("General");
            Then.onTheZC_D_MCH_SO_U_DATAObjectPageGenerated.iCheckSection({ section: "General" });
            When.onTheZC_D_MCH_SO_U_DATAObjectPageGenerated.iPressSectionIconTabFilterButton("ManageFile");
            Then.onTheZC_D_MCH_SO_U_DATAObjectPageGenerated.iCheckSection({ section: "ManageFile" });
            Then.onTheZC_D_MCH_SO_U_DATAObjectPageGenerated.onTable({ property: "_ManageFile" }).iCheckAction("Download Template", { enabled: true });
            // When.onTheZC_D_MCH_SO_U_DATAObjectPageGenerated.onTable({ property: "_ManageFile" }).iPressAction("Download Template");
            Then.onTheZC_D_MCH_SO_U_DATAObjectPageGenerated.onTable({ property: "_ManageFile" }).iCheckColumns({"Uuid":{"header":"UUID"},"Zcount":{"header":"No."},"Status":{"header":"Status"},"Attachment":{"header":"Attachment"},"Mimetype":{"header":"Mime type"},"Filename":{"header":"File name"},"Countline":{"header":"Total line of File"},"Createdbyuser":{"header":"Created By"},"Createddate":{"header":"Created On"},"Changedbyuser":{"header":"Changed By"},"Changeddate":{"header":"Changed On"}});
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});