/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ZC_EMPLOYEEObjectPageObjectPage journey");

        opaTest("Navigate to ZC_EMPLOYEEObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheZC_EMPLOYEEListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheZC_EMPLOYEEListGenerated.onTable().iCheckRows();
            When.onTheZC_EMPLOYEEListGenerated.onTable().iPressRow(0);

            Then.onTheZC_EMPLOYEEObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheZC_EMPLOYEEObjectPageGenerated.iCheckSection({ section: "GeneralInfo" });
            Then.onTheZC_EMPLOYEEObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "EmployeeUUID" });
            Then.onTheZC_EMPLOYEEObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "EmployeeCode" });
            Then.onTheZC_EMPLOYEEObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "EmployeeName" });
            Then.onTheZC_EMPLOYEEObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "HireDate" });
            Then.onTheZC_EMPLOYEEObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "CreatedBy" });
            Then.onTheZC_EMPLOYEEObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "CreatedAt" });
            Then.onTheZC_EMPLOYEEObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "LastChangedBy" });
            Then.onTheZC_EMPLOYEEObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "LocalLastChangedAt" });
            Then.onTheZC_EMPLOYEEObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "LastChangedAt" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});