/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ZC_EMPLOYEEListListReport journey");

        const defaultTableId = "";

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheZC_EMPLOYEEListGenerated.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheZC_EMPLOYEEListGenerated.onFilterBar().iCheckFilterField({ property: "EmployeeUUID" });
            Then.onTheZC_EMPLOYEEListGenerated.onFilterBar().iCheckFilterField({ property: "EmployeeCode" });
            Then.onTheZC_EMPLOYEEListGenerated.onFilterBar().iCheckFilterField({ property: "EmployeeName" });
            Then.onTheZC_EMPLOYEEListGenerated.onFilterBar().iCheckFilterField({ property: "HireDate" });
            Then.onTheZC_EMPLOYEEListGenerated.onFilterBar().iCheckFilterField({ property: "CreatedBy" });
            Then.onTheZC_EMPLOYEEListGenerated.onFilterBar().iCheckFilterField({ property: "CreatedAt" });
            Then.onTheZC_EMPLOYEEListGenerated.onFilterBar().iCheckFilterField({ property: "LastChangedBy" });
            Then.onTheZC_EMPLOYEEListGenerated.onFilterBar().iCheckFilterField({ property: "LocalLastChangedAt" });
            Then.onTheZC_EMPLOYEEListGenerated.onFilterBar().iCheckFilterField({ property: "LastChangedAt" });
        });

        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onTheZC_EMPLOYEEListGenerated.onFilterBar().iChangeSearchField("Search Term");
        //     When.onTheZC_EMPLOYEEListGenerated.onFilterBar().iExecuteSearch();
        //     Then.onTheZC_EMPLOYEEListGenerated.onTable(defaultTableId).iCheckRows();
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheZC_EMPLOYEEListGenerated.onTable(defaultTableId).iCheckColumns(undefined, {"EmployeeUUID":{"header":"Mã UUID nhân viên"},"EmployeeCode":{"header":"Mã nhân viên"},"EmployeeName":{"header":"Tên nhân viên"},"HireDate":{"header":"Ngày vào làm"},"CreatedBy":{"header":"Người tạo"},"CreatedAt":{"header":"Ngày tạo"},"LastChangedBy":{"header":"Người thay đổi cuối"},"LocalLastChangedAt":{"header":"Ngày thay đổi cục bộ cuối"},"LastChangedAt":{"header":"Ngày thay đổi cuối"}});
        });

        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            When.onTheZC_EMPLOYEEListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheZC_EMPLOYEEListGenerated.onTable(defaultTableId).iCheckRows();
            When.onTheZC_EMPLOYEEListGenerated.onTable(defaultTableId).iPressRow(0);
            Then.onTheZC_EMPLOYEEObjectPageGenerated.iSeeThisPage();
        });

        opaTest("Teardown", function (Given, When, Then) {
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});