/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ZC_M_MCH_SO_U_FILEObjectPageObjectPage journey");

        opaTest("Navigate to ZC_M_MCH_SO_U_FILEObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onTheZC_M_MCH_SO_U_FILEListGenerated.onFilterBar().iExecuteSearch();

            Then.onTheZC_M_MCH_SO_U_FILEListGenerated.onTable().iCheckRows();
            When.onTheZC_M_MCH_SO_U_FILEListGenerated.onTable().iPressRow(0);

            Then.onTheZC_M_MCH_SO_U_FILEObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheZC_M_MCH_SO_U_FILEObjectPageGenerated.iCheckNumberOfSections(2);
            When.onTheZC_M_MCH_SO_U_FILEObjectPageGenerated.iPressSectionIconTabFilterButton("General");
            Then.onTheZC_M_MCH_SO_U_FILEObjectPageGenerated.iCheckSection({ section: "General" });
            When.onTheZC_M_MCH_SO_U_FILEObjectPageGenerated.iPressSectionIconTabFilterButton("Items");
            Then.onTheZC_M_MCH_SO_U_FILEObjectPageGenerated.iCheckSection({ section: "Items" });
            Then.onTheZC_M_MCH_SO_U_FILEObjectPageGenerated.onTable({ property: "_DataFile" }).iCheckAction("Post Document" /* , { enabled: true } */);
            // When.onTheZC_M_MCH_SO_U_FILEObjectPageGenerated.onTable({ property: "_DataFile" }).iPressAction("Post Document");
            Then.onTheZC_M_MCH_SO_U_FILEObjectPageGenerated.onTable({ property: "_DataFile" }).iCheckColumns({"Type":{"header":"Type"},"Status":{"header":"Status"},"Uuid":{"header":"Message Type"},"SalesOrder":{"header":"Sales Order"},"SalesOrderItem":{"header":"Item"},"Material":{"header":"Material"},"Plant":{"header":"Plant"},"OrderQuantity":{"header":"Order Qty"},"SalesUnit":{"header":"Base Unit of Measure"},"ConditionType":{"header":"Condition Type"},"ConditionAmount":{"header":"Condition Amount"},"Currency":{"header":"Currency"},"ConditionPricingUnit":{"header":"Pricing Unit"},"TextPriceApproval":{"header":"Price Approval"},"TextOrderTolerance":{"header":"Order Tolerance"},"TextSalesNoteCustomer":{"header":"Sales Note (Customer)"},"CustomerReference":{"header":"Customer Reference"},"Messagetype":{"header":"Message Type"},"Message":{"header":"Message"},"CreatedBy":{"header":"Created By"},"CreatedAt":{"header":"Created On"},"LastChangedBy":{"header":"Changed By"},"LastChangedAt":{"header":"Changed On"}});
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});