/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ZC_M_CAN_MATDOCObjectPageObjectPage journey");

        opaTest("Navigate to ZC_M_CAN_MATDOCObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheZC_M_CAN_MATDOCListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheZC_M_CAN_MATDOCListGenerated.onTable().iCheckRows();
            When.onTheZC_M_CAN_MATDOCListGenerated.onTable().iPressRow(0);

            Then.onTheZC_M_CAN_MATDOCObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check the General section of the Object Page", function (_Given, _When, Then) {
            Then.onTheZC_M_CAN_MATDOCObjectPageGenerated.iCheckSection({ section: "General" });
            Then.onTheZC_M_CAN_MATDOCObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "MaterialDocument" });
            Then.onTheZC_M_CAN_MATDOCObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "MaterialDocumentItem" });
            Then.onTheZC_M_CAN_MATDOCObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "MaterialDocumentYear" });
            Then.onTheZC_M_CAN_MATDOCObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "PostingDate" });
            Then.onTheZC_M_CAN_MATDOCObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "ReversedMaterialDocument" });
            Then.onTheZC_M_CAN_MATDOCObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "ReversedMatdocItem" });
            Then.onTheZC_M_CAN_MATDOCObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "ItemHasBeenCanceled" });
            Then.onTheZC_M_CAN_MATDOCObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "HasReversalMovementType" });
        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});