/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ZC_TBTON_NGCObjectPageObjectPage journey");

        opaTest("Navigate to ZC_TBTON_NGCObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheZC_TBTON_NGCListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheZC_TBTON_NGCListGenerated.onTable().iCheckRows();
            When.onTheZC_TBTON_NGCListGenerated.onTable().iPressRow(0);

            Then.onTheZC_TBTON_NGCObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheZC_TBTON_NGCObjectPageGenerated.iCheckSection({ section: "GeneralInfo" });
            Then.onTheZC_TBTON_NGCObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "Zper" });
            Then.onTheZC_TBTON_NGCObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "Material" });
            Then.onTheZC_TBTON_NGCObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "Plant" });
            Then.onTheZC_TBTON_NGCObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "Supplier" });
            Then.onTheZC_TBTON_NGCObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "PurchaseOrder" });
            Then.onTheZC_TBTON_NGCObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "TotalStock" });
            Then.onTheZC_TBTON_NGCObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "BaseUnit" });
            Then.onTheZC_TBTON_NGCObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "ValuationType" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});