/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ZC_TB_KB_NHANCONG_QRListListReport journey");

        const defaultTableId = "";

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheZC_TB_KB_NHANCONG_QRListGenerated.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheZC_TB_KB_NHANCONG_QRListGenerated.onFilterBar().iCheckFilterField({ property: "WorkCenter" });
            Then.onTheZC_TB_KB_NHANCONG_QRListGenerated.onFilterBar().iCheckFilterField({ property: "Plant" });
            Then.onTheZC_TB_KB_NHANCONG_QRListGenerated.onFilterBar().iCheckFilterField({ property: "WorkerID" });
            Then.onTheZC_TB_KB_NHANCONG_QRListGenerated.onFilterBar().iCheckFilterField({ property: "WorkerName" });
            Then.onTheZC_TB_KB_NHANCONG_QRListGenerated.onFilterBar().iCheckFilterField({ property: "FromDate" });
            Then.onTheZC_TB_KB_NHANCONG_QRListGenerated.onFilterBar().iCheckFilterField({ property: "ToDate" });
        });

        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onTheZC_TB_KB_NHANCONG_QRListGenerated.onFilterBar().iChangeSearchField("Search Term");
        //     When.onTheZC_TB_KB_NHANCONG_QRListGenerated.onFilterBar().iExecuteSearch();
        //     Then.onTheZC_TB_KB_NHANCONG_QRListGenerated.onTable(defaultTableId).iCheckRows();
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheZC_TB_KB_NHANCONG_QRListGenerated.onTable(defaultTableId).iCheckColumns(undefined, {"WorkCenter":{"header":"Work Center"},"Plant":{"header":"Plant"},"WorkerID":{"header":"Mã Nhân Công"},"WorkerName":{"header":"Tên Nhân Công"},"FromDate":{"header":"Từ Ngày"},"ToDate":{"header":"Đến Ngày"}});
        });

        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            When.onTheZC_TB_KB_NHANCONG_QRListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheZC_TB_KB_NHANCONG_QRListGenerated.onTable(defaultTableId).iCheckRows();
            When.onTheZC_TB_KB_NHANCONG_QRListGenerated.onTable(defaultTableId).iPressRow(0);
            Then.onTheZC_TB_KB_NHANCONG_QRObjectPageGenerated.iSeeThisPage();
        });

        opaTest("Teardown", function (Given, When, Then) {
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});