/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ZC_TBBANK_UPLListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheZC_TBBANK_UPLListGenerated.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheZC_TBBANK_UPLListGenerated.onFilterBar().iCheckFilterField("UUID");
            Then.onTheZC_TBBANK_UPLListGenerated.onFilterBar().iCheckFilterField("Bank Country");
            Then.onTheZC_TBBANK_UPLListGenerated.onFilterBar().iCheckFilterField("Bank key");
            Then.onTheZC_TBBANK_UPLListGenerated.onFilterBar().iCheckFilterField("LongBankName");
            Then.onTheZC_TBBANK_UPLListGenerated.onFilterBar().iCheckFilterField("LongBankBranch");
            Then.onTheZC_TBBANK_UPLListGenerated.onFilterBar().iCheckFilterField("IsMarkedForDeletion");
            Then.onTheZC_TBBANK_UPLListGenerated.onFilterBar().iCheckFilterField("Status");
            Then.onTheZC_TBBANK_UPLListGenerated.onFilterBar().iCheckFilterField("Message");
            Then.onTheZC_TBBANK_UPLListGenerated.onFilterBar().iCheckFilterField("Created By");
            Then.onTheZC_TBBANK_UPLListGenerated.onFilterBar().iCheckFilterField("Created On");
            Then.onTheZC_TBBANK_UPLListGenerated.onFilterBar().iCheckFilterField("Changed By");
            Then.onTheZC_TBBANK_UPLListGenerated.onFilterBar().iCheckFilterField("Changed On");
        });

        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onTheZC_TBBANK_UPLListGenerated.onFilterBar().iChangeSearchField("Search Term");
        //     When.onTheZC_TBBANK_UPLListGenerated.onFilterBar().iExecuteSearch();
        //     Then.onTheZC_TBBANK_UPLListGenerated.onTable().iCheckRows();
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheZC_TBBANK_UPLListGenerated.onTable().iCheckColumns(undefined, {"UUID":{"header":"UUID"},"BankCountry":{"header":"Bank Country"},"BankInternalID":{"header":"Bank key"},"LongBankName":{"header":"Bank Name"},"LongBankBranch":{"header":"Bank Branch"},"IsMarkedForDeletion":{"header":"IsMarkedForDeletion"},"Status":{"header":"Status"},"Message":{"header":"Message"},"Createdbyuser":{"header":"Created By"},"Createddate":{"header":"Created On"},"Changedbyuser":{"header":"Changed By"},"Changeddate":{"header":"Changed On"}});

        });



        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            When.onTheZC_TBBANK_UPLListGenerated.onFilterBar().iExecuteSearch();
            
            Then.onTheZC_TBBANK_UPLListGenerated.onTable().iCheckRows();

            When.onTheZC_TBBANK_UPLListGenerated.onTable().iPressRow(0);
            Then.onTheZC_TBBANK_UPLObjectPageGenerated.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});