/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ZC_TB_KB_NHANCONG_QRObjectPageObjectPage journey");

        opaTest("Navigate to ZC_TB_KB_NHANCONG_QRObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheZC_TB_KB_NHANCONG_QRListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheZC_TB_KB_NHANCONG_QRListGenerated.onTable().iCheckRows();
            When.onTheZC_TB_KB_NHANCONG_QRListGenerated.onTable().iPressRow(0);

            Then.onTheZC_TB_KB_NHANCONG_QRObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheZC_TB_KB_NHANCONG_QRObjectPageGenerated.iCheckSection({ section: "KB_NHANCONG" });
            Then.onTheZC_TB_KB_NHANCONG_QRObjectPageGenerated.onForm({ section: "KB_NHANCONG" }).iCheckField({ property: "WorkCenter" });
            Then.onTheZC_TB_KB_NHANCONG_QRObjectPageGenerated.onForm({ section: "KB_NHANCONG" }).iCheckField({ property: "Plant" });
            Then.onTheZC_TB_KB_NHANCONG_QRObjectPageGenerated.onForm({ section: "KB_NHANCONG" }).iCheckField({ property: "WorkerID" });
            Then.onTheZC_TB_KB_NHANCONG_QRObjectPageGenerated.onForm({ section: "KB_NHANCONG" }).iCheckField({ property: "WorkerName" });
            Then.onTheZC_TB_KB_NHANCONG_QRObjectPageGenerated.onForm({ section: "KB_NHANCONG" }).iCheckField({ property: "FromDate" });
            Then.onTheZC_TB_KB_NHANCONG_QRObjectPageGenerated.onForm({ section: "KB_NHANCONG" }).iCheckField({ property: "ToDate" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});