/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ZC_TBBANK_UPLObjectPageObjectPage journey");

        opaTest("Navigate to ZC_TBBANK_UPLObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheZC_TBBANK_UPLListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheZC_TBBANK_UPLListGenerated.onTable().iCheckRows();
            When.onTheZC_TBBANK_UPLListGenerated.onTable().iPressRow(0);

            Then.onTheZC_TBBANK_UPLObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheZC_TBBANK_UPLObjectPageGenerated.iCheckSection({ section: "GeneralInfo" });
            Then.onTheZC_TBBANK_UPLObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "UUID" });
            Then.onTheZC_TBBANK_UPLObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "BankCountry" });
            Then.onTheZC_TBBANK_UPLObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "BankInternalID" });
            Then.onTheZC_TBBANK_UPLObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "LongBankName" });
            Then.onTheZC_TBBANK_UPLObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "LongBankBranch" });
            Then.onTheZC_TBBANK_UPLObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "IsMarkedForDeletion" });
            Then.onTheZC_TBBANK_UPLObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "Status" });
            Then.onTheZC_TBBANK_UPLObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "Message" });
            Then.onTheZC_TBBANK_UPLObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "Createdbyuser" });
            Then.onTheZC_TBBANK_UPLObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "Createddate" });
            Then.onTheZC_TBBANK_UPLObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "Changedbyuser" });
            Then.onTheZC_TBBANK_UPLObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "Changeddate" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});