/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ZC_TBTON_NGCListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheZC_TBTON_NGCListGenerated.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheZC_TBTON_NGCListGenerated.onFilterBar().iCheckFilterField("Kỳ");
            Then.onTheZC_TBTON_NGCListGenerated.onFilterBar().iCheckFilterField("Mã hàng");
            Then.onTheZC_TBTON_NGCListGenerated.onFilterBar().iCheckFilterField("Plant");
            Then.onTheZC_TBTON_NGCListGenerated.onFilterBar().iCheckFilterField("Nhà gia công");
            Then.onTheZC_TBTON_NGCListGenerated.onFilterBar().iCheckFilterField("PO");
        });

        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onTheZC_TBTON_NGCListGenerated.onFilterBar().iChangeSearchField("Search Term");
        //     When.onTheZC_TBTON_NGCListGenerated.onFilterBar().iExecuteSearch();
        //     Then.onTheZC_TBTON_NGCListGenerated.onTable().iCheckRows();
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            // Then.onTheZC_TBTON_NGCListGenerated.onTable().iPressAction("Tính tồn NGC");
            Then.onTheZC_TBTON_NGCListGenerated.onTable().iCheckAction("Tính tồn NGC", { enabled: true });
            Then.onTheZC_TBTON_NGCListGenerated.onTable().iCheckColumns(undefined, {"Zper":{"header":"Kỳ"},"Material":{"header":"Mã hàng"},"Plant":{"header":"Plant"},"Supplier":{"header":"Nhà gia công"},"PurchaseOrder":{"header":"PO"},"TotalStock":{"header":"Total Stock"},"BaseUnit":{"header":"Đơn vị tính"},"ValuationType":{"header":"Valuation Type"}});

        });



        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            When.onTheZC_TBTON_NGCListGenerated.onFilterBar().iExecuteSearch();
            
            Then.onTheZC_TBTON_NGCListGenerated.onTable().iCheckRows();

            When.onTheZC_TBTON_NGCListGenerated.onTable().iPressRow(0);
            Then.onTheZC_TBTON_NGCObjectPageGenerated.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});