/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ZCE_NGC_STOCK_CUSTOMObjectPageObjectPage journey");

        opaTest("Navigate to ZCE_NGC_STOCK_CUSTOMObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheZCE_NGC_STOCK_CUSTOMListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheZCE_NGC_STOCK_CUSTOMListGenerated.onTable().iCheckRows();
            When.onTheZCE_NGC_STOCK_CUSTOMListGenerated.onTable().iPressRow(0);

            Then.onTheZCE_NGC_STOCK_CUSTOMObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheZCE_NGC_STOCK_CUSTOMObjectPageGenerated.iCheckSection({ section: "GeneratedFacet1" });
            Then.onTheZCE_NGC_STOCK_CUSTOMObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "STTKey" });
            Then.onTheZCE_NGC_STOCK_CUSTOMObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "zper" });
            Then.onTheZCE_NGC_STOCK_CUSTOMObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Supplier" });
            Then.onTheZCE_NGC_STOCK_CUSTOMObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "PurchaseOrder" });
            Then.onTheZCE_NGC_STOCK_CUSTOMObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "PurchaseOrderItem" });
            Then.onTheZCE_NGC_STOCK_CUSTOMObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Material" });
            Then.onTheZCE_NGC_STOCK_CUSTOMObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "ProductGroup" });
            Then.onTheZCE_NGC_STOCK_CUSTOMObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "BaseUnit" });
            Then.onTheZCE_NGC_STOCK_CUSTOMObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "ValuationType" });
            Then.onTheZCE_NGC_STOCK_CUSTOMObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "CustomsCode" });
            Then.onTheZCE_NGC_STOCK_CUSTOMObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "OpeningStockQty" });
            Then.onTheZCE_NGC_STOCK_CUSTOMObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "IncreaseQty" });
            Then.onTheZCE_NGC_STOCK_CUSTOMObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "ReturnQty" });
            Then.onTheZCE_NGC_STOCK_CUSTOMObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "POComponentQty" });
            Then.onTheZCE_NGC_STOCK_CUSTOMObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "BOMQty" });
            Then.onTheZCE_NGC_STOCK_CUSTOMObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "LossQty" });
            Then.onTheZCE_NGC_STOCK_CUSTOMObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "ConsumptionQty" });
            Then.onTheZCE_NGC_STOCK_CUSTOMObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "ClosingStockQty" });
            Then.onTheZCE_NGC_STOCK_CUSTOMObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "BOMRatio" });
            Then.onTheZCE_NGC_STOCK_CUSTOMObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "FinishedGoodMaterial" });
            Then.onTheZCE_NGC_STOCK_CUSTOMObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "POOrderQty" });
            Then.onTheZCE_NGC_STOCK_CUSTOMObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "FGRestockQty" });
            Then.onTheZCE_NGC_STOCK_CUSTOMObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "FGReturnQty" });
            Then.onTheZCE_NGC_STOCK_CUSTOMObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "RemainingPOQty" });
            Then.onTheZCE_NGC_STOCK_CUSTOMObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "POStatus" });
            Then.onTheZCE_NGC_STOCK_CUSTOMObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Plant" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});