/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ZCE_NGC_STOCK_CUSTOMListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheZCE_NGC_STOCK_CUSTOMListGenerated.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheZCE_NGC_STOCK_CUSTOMListGenerated.onFilterBar().iCheckFilterField("Nhà GC");
            Then.onTheZCE_NGC_STOCK_CUSTOMListGenerated.onFilterBar().iCheckFilterField("Period");
            Then.onTheZCE_NGC_STOCK_CUSTOMListGenerated.onFilterBar().iCheckFilterField("PO");
        });

        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onTheZCE_NGC_STOCK_CUSTOMListGenerated.onFilterBar().iChangeSearchField("Search Term");
        //     When.onTheZCE_NGC_STOCK_CUSTOMListGenerated.onFilterBar().iExecuteSearch();
        //     Then.onTheZCE_NGC_STOCK_CUSTOMListGenerated.onTable().iCheckRows();
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheZCE_NGC_STOCK_CUSTOMListGenerated.onTable().iCheckColumns(undefined, {"STTKey":{"header":"STT"},"Supplier":{"header":"Nhà GC"},"PurchaseOrder":{"header":"PO"},"PurchaseOrderItem":{"header":"Item"},"Material":{"header":"Mã hàng"},"ProductGroup":{"header":"Nhóm hàng"},"BaseUnit":{"header":"ĐVT"},"ValuationType":{"header":"Valuation Type"},"CustomsCode":{"header":"Mã hải quan"},"OpeningStockQty":{"header":"SL tồn đầu"},"IncreaseQty":{"header":"SL tăng"},"ReturnQty":{"header":"SL NVL trả về"},"POComponentQty":{"header":"SL theo Component PO"},"BOMQty":{"header":"SL BOM"},"LossQty":{"header":"SL hao hụt"},"ConsumptionQty":{"header":"SL Tiêu Hao"},"BOMRatio":{"header":"Tỷ lệ BOM"},"FinishedGoodMaterial":{"header":"Mã TP GC"},"POOrderQty":{"header":"Số lượng theo PO"},"FGRestockQty":{"header":"Số lượng TP nhập theo PO"},"FGReturnQty":{"header":"Số lượng trả hàng"},"RemainingPOQty":{"header":"Còn lại"},"POStatus":{"header":"Trạng thái PO"},"Plant":{"header":"Plant"}});

        });



        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            When.onTheZCE_NGC_STOCK_CUSTOMListGenerated.onFilterBar().iExecuteSearch();
            
            Then.onTheZCE_NGC_STOCK_CUSTOMListGenerated.onTable().iCheckRows();

            When.onTheZCE_NGC_STOCK_CUSTOMListGenerated.onTable().iPressRow(0);
            Then.onTheZCE_NGC_STOCK_CUSTOMObjectPageGenerated.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});