/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("zce_ciListListReport journey");

        const defaultTableId = "";

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onThezce_ciListGenerated.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onThezce_ciListGenerated.onFilterBar().iCheckFilterField({ property: "SalesOrganization" });
            Then.onThezce_ciListGenerated.onFilterBar().iCheckFilterField({ property: "DateCI" });
            Then.onThezce_ciListGenerated.onFilterBar().iCheckFilterField({ property: "ProFormaInvoice" });
            Then.onThezce_ciListGenerated.onFilterBar().iCheckFilterField({ property: "Customer" });
        });

        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onThezce_ciListGenerated.onFilterBar().iChangeSearchField("Search Term");
        //     When.onThezce_ciListGenerated.onFilterBar().iExecuteSearch();
        //     Then.onThezce_ciListGenerated.onTable(defaultTableId).iCheckRows();
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onThezce_ciListGenerated.onTable(defaultTableId).iCheckColumns(undefined, {"ProFormaInvoice":{"header":"Pro-forma Invoice"},"ToCI":{"header":"To"},"Invoice":{"header":"Invoice"},"DateCI":{"header":"Date"},"PO":{"header":"PO"},"LOT":{"header":"LOT"},"Item":{"header":"Item"},"Material":{"header":"Material"},"AZTID":{"header":"AZT ID (Description)"},"Quantity":{"header":"Quantity"},"UnitPrice":{"header":"Unit Price"},"Amount":{"header":"Amount"},"MBL":{"header":"MB/L"},"HBL":{"header":"HB/L"},"VesselName":{"header":"Vessel Name"},"ETD":{"header":"ETD"},"ETA":{"header":"ETA"},"ContainerNo":{"header":"Container No"},"PortOfLoading":{"header":"Port Of Loading"},"PortOfDestination":{"header":"Port Of Destination"},"PriceTerm":{"header":"Price Term"},"HTSCode":{"header":"HTS Code"},"CountryOfOrigin":{"header":"Country Of Origin"},"QuartzSlabs":{"header":"Quartz Slabs"},"AddCI":{"header":"Add"},"TelCI":{"header":"Tel"},"SalesOrganization":{"header":"Sales Organization"},"Customer":{"header":"Customer"}});
        });

        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            When.onThezce_ciListGenerated.onFilterBar().iExecuteSearch();
            Then.onThezce_ciListGenerated.onTable(defaultTableId).iCheckRows();
            When.onThezce_ciListGenerated.onTable(defaultTableId).iPressRow(0);
            Then.onThezce_ciObjectPageGenerated.iSeeThisPage();
        });

        opaTest("Teardown", function (Given, When, Then) {
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});