/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("zce_ciObjectPageObjectPage journey");

        opaTest("Navigate to zce_ciObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onThezce_ciListGenerated.onFilterBar().iExecuteSearch();
            Then.onThezce_ciListGenerated.onTable().iCheckRows();
            When.onThezce_ciListGenerated.onTable().iPressRow(0);

            Then.onThezce_ciObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onThezce_ciObjectPageGenerated.iCheckSection({ section: "GeneralInfo" });
            Then.onThezce_ciObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "ProFormaInvoice" });
            Then.onThezce_ciObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "ToCI" });
            Then.onThezce_ciObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "Invoice" });
            Then.onThezce_ciObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "DateCI" });
            Then.onThezce_ciObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "PO" });
            Then.onThezce_ciObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "LOT" });
            Then.onThezce_ciObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "Item" });
            Then.onThezce_ciObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "Material" });
            Then.onThezce_ciObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "AZTID" });
            Then.onThezce_ciObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "Quantity" });
            Then.onThezce_ciObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "UnitPrice" });
            Then.onThezce_ciObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "Amount" });
            Then.onThezce_ciObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "MBL" });
            Then.onThezce_ciObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "HBL" });
            Then.onThezce_ciObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "VesselName" });
            Then.onThezce_ciObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "ETD" });
            Then.onThezce_ciObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "ETA" });
            Then.onThezce_ciObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "ContainerNo" });
            Then.onThezce_ciObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "PortOfLoading" });
            Then.onThezce_ciObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "PortOfDestination" });
            Then.onThezce_ciObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "PriceTerm" });
            Then.onThezce_ciObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "HTSCode" });
            Then.onThezce_ciObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "CountryOfOrigin" });
            Then.onThezce_ciObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "QuartzSlabs" });
            Then.onThezce_ciObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "AddCI" });
            Then.onThezce_ciObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "TelCI" });
            Then.onThezce_ciObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "Customer" });
            Then.onThezce_ciObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "SalesOrganization" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});