/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ZI_ORD_CONF_ITEMObjectPageObjectPage journey");

        opaTest("Navigate to ZI_ORD_CONF_ITEMObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onTheZI_ORD_CONF_ITEMListGenerated.onFilterBar().iExecuteSearch();

            Then.onTheZI_ORD_CONF_ITEMListGenerated.onTable().iCheckRows();
            When.onTheZI_ORD_CONF_ITEMListGenerated.onTable().iPressRow(0);

            Then.onTheZI_ORD_CONF_ITEMObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheZI_ORD_CONF_ITEMObjectPageGenerated.iCheckNumberOfSections(5);
            When.onTheZI_ORD_CONF_ITEMObjectPageGenerated.iPressSectionIconTabFilterButton("General");
            Then.onTheZI_ORD_CONF_ITEMObjectPageGenerated.iCheckSection({ section: "General" });
            When.onTheZI_ORD_CONF_ITEMObjectPageGenerated.iPressSectionIconTabFilterButton("Customer");
            Then.onTheZI_ORD_CONF_ITEMObjectPageGenerated.iCheckSection({ section: "Customer" });
            When.onTheZI_ORD_CONF_ITEMObjectPageGenerated.iPressSectionIconTabFilterButton("Item");
            Then.onTheZI_ORD_CONF_ITEMObjectPageGenerated.iCheckSection({ section: "Item" });
            When.onTheZI_ORD_CONF_ITEMObjectPageGenerated.iPressSectionIconTabFilterButton("Pricing");
            Then.onTheZI_ORD_CONF_ITEMObjectPageGenerated.iCheckSection({ section: "Pricing" });
            When.onTheZI_ORD_CONF_ITEMObjectPageGenerated.iPressSectionIconTabFilterButton("Totals");
            Then.onTheZI_ORD_CONF_ITEMObjectPageGenerated.iCheckSection({ section: "Totals" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});