/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ZI_ORD_CONF_ITEMListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheZI_ORD_CONF_ITEMListGenerated.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheZI_ORD_CONF_ITEMListGenerated.onFilterBar().iCheckFilterField("Sales Organization");
            Then.onTheZI_ORD_CONF_ITEMListGenerated.onFilterBar().iCheckFilterField("Sales Order");
            Then.onTheZI_ORD_CONF_ITEMListGenerated.onFilterBar().iCheckFilterField("Ngày chứng từ");
            Then.onTheZI_ORD_CONF_ITEMListGenerated.onFilterBar().iCheckFilterField("Mã khách hàng");
            Then.onTheZI_ORD_CONF_ITEMListGenerated.onFilterBar().iCheckFilterField("Số hợp đồng khách hàng");
            Then.onTheZI_ORD_CONF_ITEMListGenerated.onFilterBar().iCheckFilterField("Mã sản phẩm");
        });

        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onTheZI_ORD_CONF_ITEMListGenerated.onFilterBar().iChangeSearchField("Search Term");
        //     When.onTheZI_ORD_CONF_ITEMListGenerated.onFilterBar().iExecuteSearch();
        //     Then.onTheZI_ORD_CONF_ITEMListGenerated.onTable().iCheckRows();
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            // Then.onTheZI_ORD_CONF_ITEMListGenerated.onTable().iPressAction("Pdf");
            Then.onTheZI_ORD_CONF_ITEMListGenerated.onTable().iCheckAction("Pdf", { enabled: false });
            Then.onTheZI_ORD_CONF_ITEMListGenerated.onTable().iCheckColumns(undefined, {"SalesOrder":{"header":"Sales Order"},"SalesOrderItem":{"header":"Sales Order Item"},"DistributionChannel":{"header":"Kênh phân phối"},"DocumentDate":{"header":"Ngày chứng từ"},"SoldToParty":{"header":"Mã khách hàng"},"CustomerName":{"header":"Tên khách hàng"},"BusinessPartner":{"header":"Mã khách hàng"},"Material":{"header":"Mã sản phẩm"},"ItemDescription":{"header":"Mô tả sản phẩm"},"Quality":{"header":"Chất lượng"},"OrderQuantity":{"header":"Số lượng (tấm)"},"QuantityM2":{"header":"Số lượng (m²)"},"UnitPrice":{"header":"Đơn giá"},"Amount":{"header":"Thành tiền"}});

        });



        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            When.onTheZI_ORD_CONF_ITEMListGenerated.onFilterBar().iExecuteSearch();
            
            Then.onTheZI_ORD_CONF_ITEMListGenerated.onTable().iCheckRows();

            When.onTheZI_ORD_CONF_ITEMListGenerated.onTable().iPressRow(0);
            Then.onTheZI_ORD_CONF_ITEMObjectPageGenerated.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});