/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ZR_MFGORD_OPER_WCListListReport journey");

        const defaultTableId = "";

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheZR_MFGORD_OPER_WCListGenerated.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheZR_MFGORD_OPER_WCListGenerated.onFilterBar().iCheckFilterField({ property: "ManufacturingOrder" });
            Then.onTheZR_MFGORD_OPER_WCListGenerated.onFilterBar().iCheckFilterField({ property: "ManufacturingOrderSequence" });
            Then.onTheZR_MFGORD_OPER_WCListGenerated.onFilterBar().iCheckFilterField({ property: "WorkCenter" });
        });

        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onTheZR_MFGORD_OPER_WCListGenerated.onFilterBar().iChangeSearchField("Search Term");
        //     When.onTheZR_MFGORD_OPER_WCListGenerated.onFilterBar().iExecuteSearch();
        //     Then.onTheZR_MFGORD_OPER_WCListGenerated.onTable(defaultTableId).iCheckRows();
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheZR_MFGORD_OPER_WCListGenerated.onTable(defaultTableId).iCheckColumns(undefined, {"ManufacturingOrder":{"header":"Lệnh sản xuất"},"ManufacturingOrderSequence":{"header":"Công đoạn"},"MfgOrderOperationText":{"header":"Tên công đoạn"},"WorkCenter":{"header":"Work Center"},"WorkCenterDescription":{"header":"Mô tả WC"},"OpPlannedTotalQuantity":{"header":"SL công đoạn"}});
        });

        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            When.onTheZR_MFGORD_OPER_WCListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheZR_MFGORD_OPER_WCListGenerated.onTable(defaultTableId).iCheckRows();
            When.onTheZR_MFGORD_OPER_WCListGenerated.onTable(defaultTableId).iPressRow(0);
            Then.onTheZR_MFGORD_OPER_WCObjectPageGenerated.iSeeThisPage();
        });

        opaTest("Teardown", function (Given, When, Then) {
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});