/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ZR_MFGORD_OPER_WCObjectPageObjectPage journey");

        opaTest("Navigate to ZR_MFGORD_OPER_WCObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheZR_MFGORD_OPER_WCListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheZR_MFGORD_OPER_WCListGenerated.onTable().iCheckRows();
            When.onTheZR_MFGORD_OPER_WCListGenerated.onTable().iPressRow(0);

            Then.onTheZR_MFGORD_OPER_WCObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheZR_MFGORD_OPER_WCObjectPageGenerated.iCheckSection({ section: "GeneralInfo" });
            Then.onTheZR_MFGORD_OPER_WCObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "ManufacturingOrder" });
            Then.onTheZR_MFGORD_OPER_WCObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "ManufacturingOrderSequence" });
            Then.onTheZR_MFGORD_OPER_WCObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "MfgOrderOperationText" });
            Then.onTheZR_MFGORD_OPER_WCObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "WorkCenter" });
            Then.onTheZR_MFGORD_OPER_WCObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "WorkCenterDescription" });
            Then.onTheZR_MFGORD_OPER_WCObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "OpPlannedTotalQuantity" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});