/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("HHDVHeadListListReport journey");

        const defaultTableId = "";

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheHHDVHeadListGenerated.iSeeThisPage();
        });


        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onTheHHDVHeadListGenerated.onFilterBar().iChangeSearchField("Search Term");
        //     When.onTheHHDVHeadListGenerated.onFilterBar().iExecuteSearch();
        //     Then.onTheHHDVHeadListGenerated.onTable(defaultTableId).iCheckRows();
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheHHDVHeadListGenerated.onTable(defaultTableId).iCheckColumns(undefined, {"InvoiceId":{"header":"InvoiceId"},"InvoiceType":{"header":"InvoiceType"},"AdjustmentType":{"header":"AdjustmentType"},"TemplateCode":{"header":"TemplateCode"},"InvoiceSeri":{"header":"InvoiceSeri"},"InvoiceNumber":{"header":"InvoiceNumber"},"InvoiceNo":{"header":"InvoiceNo"},"Currency":{"header":"Currency"},"Total":{"header":"Total"},"IssueDate":{"header":"IssueDate"},"IssueDateStr":{"header":"IssueDateStr"},"State":{"header":"State"},"RequestDate":{"header":"RequestDate"},"Description":{"header":"Description"},"BuyerIdNo":{"header":"BuyerIdNo"},"StateCode":{"header":"StateCode"},"SubscriberNumber":{"header":"SubscriberNumber"},"PaymentStatus":{"header":"PaymentStatus"},"ViewStatus":{"header":"ViewStatus"},"DownloadStatus":{"header":"DownloadStatus"},"ExchangeStatus":{"header":"ExchangeStatus"},"NumOfExchange":{"header":"NumOfExchange"},"CreateTime":{"header":"CreateTime"},"ContractId":{"header":"ContractId"},"ContractNo":{"header":"ContractNo"},"SupplierTaxCode":{"header":"SupplierTaxCode"},"BuyerTaxCode":{"header":"BuyerTaxCode"},"TotalBeforeTax":{"header":"TotalBeforeTax"},"TaxAmount":{"header":"TaxAmount"},"TaxRate":{"header":"TaxRate"},"PaymentMethod":{"header":"PaymentMethod"},"PaymentTime":{"header":"PaymentTime"},"CustomerId":{"header":"CustomerId"},"NoField":{"header":"NoField"},"PaymentStatusName":{"header":"PaymentStatusName"},"BuyerName":{"header":"BuyerName"},"TransactionUuid":{"header":"TransactionUuid"},"OriginalInvoiceId":{"header":"OriginalInvoiceId"},"ListProduct":{"header":"ListProduct"},"FileName":{"header":"FileName"},"BuyerUnitName":{"header":"BuyerUnitName"},"BuyerCode":{"header":"BuyerCode"},"BuyerAddress":{"header":"BuyerAddress"},"ExchangeRate":{"header":"ExchangeRate"},"ListInfoUpdate":{"header":"ListInfoUpdate"},"ErrorCode":{"header":"ErrorCode"},"ErrorDescription":{"header":"ErrorDescription"}});
        });

        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            When.onTheHHDVHeadListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheHHDVHeadListGenerated.onTable(defaultTableId).iCheckRows();
            When.onTheHHDVHeadListGenerated.onTable(defaultTableId).iPressRow(0);
            Then.onTheHHDVHeadObjectPageGenerated.iSeeThisPage();
        });

        opaTest("Teardown", function (Given, When, Then) {
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});