/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("HHDVItemObjectPageObjectPage journey");

        opaTest("Navigate to HHDVItemObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheHHDVHeadListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheHHDVHeadListGenerated.onTable().iCheckRows();
            When.onTheHHDVHeadListGenerated.onTable().iPressRow(0);

            Then.onTheHHDVHeadObjectPageGenerated.iSeeThisPage();
            Then.onTheHHDVHeadObjectPageGenerated.onTable({ property: "_Item" }).iCheckRows();
            When.onTheHHDVHeadObjectPageGenerated.onTable({ property: "_Item" }).iPressRow(0);

            Then.onTheHHDVItemObjectPageGenerated.iSeeThisPage();
        });




        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});