/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("HHDVHeadObjectPageObjectPage journey");

        opaTest("Navigate to HHDVHeadObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheHHDVHeadListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheHHDVHeadListGenerated.onTable().iCheckRows();
            When.onTheHHDVHeadListGenerated.onTable().iPressRow(0);

            Then.onTheHHDVHeadObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheHHDVHeadObjectPageGenerated.iCheckNumberOfSections(2);
            When.onTheHHDVHeadObjectPageGenerated.iPressSectionIconTabFilterButton("General");
            Then.onTheHHDVHeadObjectPageGenerated.iCheckSection({ section: "General" });
            //When.onTheHHDVHeadObjectPageGenerated.iGoToSection({ section: "General", subSection: "BasicInfo" });
            Then.onTheHHDVHeadObjectPageGenerated.iCheckSubSection({ section: "BasicInfo" });
            Then.onTheHHDVHeadObjectPageGenerated.onForm({ section: "BasicInfo" }).iCheckField({ property: "InvoiceId" });
            Then.onTheHHDVHeadObjectPageGenerated.onForm({ section: "BasicInfo" }).iCheckField({ property: "InvoiceType" });
            Then.onTheHHDVHeadObjectPageGenerated.onForm({ section: "BasicInfo" }).iCheckField({ property: "AdjustmentType" });
            Then.onTheHHDVHeadObjectPageGenerated.onForm({ section: "BasicInfo" }).iCheckField({ property: "Currency" });
            When.onTheHHDVHeadObjectPageGenerated.iPressSectionIconTabFilterButton("Items");
            Then.onTheHHDVHeadObjectPageGenerated.iCheckSection({ section: "Items" });
            Then.onTheHHDVHeadObjectPageGenerated.onTable({ property: "_Item" }).iCheckColumns(undefined, {"InvoiceId":{"header":"InvoiceId"},"LineNumber":{"header":"LineNumber"},"Selection":{"header":"Selection"},"ItemType":{"header":"ItemType"},"ItemCode":{"header":"ItemCode"},"ItemName":{"header":"ItemName"},"UnitCode":{"header":"UnitCode"},"UnitName":{"header":"UnitName"},"Currency":{"header":"Currency"},"UnitPrice":{"header":"UnitPrice"},"Quantity":{"header":"Quantity"},"ItemTotalAmtWithoutVat":{"header":"ItemTotalAmtWithoutVat"},"ItemTotalAmtWithVat":{"header":"ItemTotalAmtWithVat"},"ItemTotalAmtAfterDiscount":{"header":"ItemTotalAmtAfterDiscount"},"ItemServiceChargePercentage":{"header":"ItemServiceChargePercentage"},"ItemServiceChargeAmount":{"header":"ItemServiceChargeAmount"},"ItemExciseTaxPercentage":{"header":"ItemExciseTaxPercentage"},"ItemExciseTaxAmount":{"header":"ItemExciseTaxAmount"},"VatPercentage":{"header":"VatPercentage"},"VatAmount":{"header":"VatAmount"},"Discount":{"header":"Discount"},"Discount2":{"header":"Discount2"},"ItemDiscount":{"header":"ItemDiscount"},"ItemNote":{"header":"ItemNote"},"BatchNo":{"header":"BatchNo"},"ExpDate":{"header":"ExpDate"},"IsIncreaseItem":{"header":"IsIncreaseItem"},"AdjustRatio":{"header":"AdjustRatio"},"AdjustIndex":{"header":"AdjustIndex"},"AdjustFactors":{"header":"AdjustFactors"},"DiscountAmount":{"header":"DiscountAmount"},"DiscountAmount2":{"header":"DiscountAmount2"},"SpecialInfo":{"header":"SpecialInfo"},"DiscountValue":{"header":"DiscountValue"},"DiscountValue2":{"header":"DiscountValue2"}});
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});